/*
  C-file generated by µC/GUI-FontConvert Demo  V2.18
  Compiled:    Jul 17 2003 at 08:42:22

  (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com

  Source file: ProFontWindows15.c
  Font:        ProFontWindows
  Height:      15
*/

#include "GUI.H"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontProFontWindows15;

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0020[ 15] = { /* code 0020 */
  XXX____X,
  _XX__XX_,
  XXX__XX_,
  __X_X_XX,
  X__XX___,
  X_XXXX_X,
  __X_XX_X,
  __XXXX__,
  XXX_X___,
  X____X_X,
  __XX__X_,
  _X_X__X_,
  ____XXX_,
  XXX____X,
  X__XX___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0021[ 15] = { /* code 0021 */
  X_X_XXXX,
  XX__X_XX,
  ____XXX_,
  XX_XXXX_,
  XXXX_XX_,
  X_X_X_XX,
  _X__X_X_,
  _X_____X,
  X_X___X_,
  ___XXXX_,
  _XX__X__,
  ___X_X_X,
  X______X,
  X___XX_X,
  ___X____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0022[ 15] = { /* code 0022 */
  _XX_X_X_,
  X___XX_X,
  X_XXXXXX,
  ____XXXX,
  __XX__XX,
  XX____XX,
  ___XXXXX,
  X___XX__,
  _XXXXX_X,
  XXX_XX__,
  X_XX_XX_,
  X_XXXXXX,
  ___XX_XX,
  ___XX__X,
  _XXX__X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0023[ 15] = { /* code 0023 */
  XXXXXXXX,
  __XX_X_X,
  ___X_XXX,
  XX_XX__X,
  XXX__X_X,
  __X_X_X_,
  _X____X_,
  __X_X___,
  ____X__X,
  ___X___X,
  XXX_X_X_,
  _XXX____,
  _XXX___X,
  __X_XX__,
  X___X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0024[ 15] = { /* code 0024 */
  XXXX___X,
  X__XXXXX,
  X_X_XXX_,
  ___X_X_X,
  ___XXXX_,
  XXX_X_X_,
  XXX_XX_X,
  _XXX_XXX,
  ___XXX__,
  ____X___,
  X_X_X_XX,
  XX__X_XX,
  X__X__XX,
  X_XXX_XX,
  _XXX__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0025[ 15] = { /* code 0025 */
  _____XX_,
  X___XXX_,
  __XX____,
  __X__XXX,
  X__XX___,
  __XX___X,
  ________,
  XXXXXX_X,
  __XXXXX_,
  __X__XXX,
  X_XXX__X,
  _X__X_XX,
  XX__XX_X,
  _XX__X_X,
  _X_XX_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0026[ 15] = { /* code 0026 */
  _____XX_,
  _X_____X,
  X____X_X,
  XXX____X,
  X____XXX,
  X_XXXXXX,
  XX___X__,
  __XX___X,
  ___XX_X_,
  _X_X____,
  X__XXXXX,
  _XXXX__X,
  XX_XX___,
  X_X__XX_,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0027[ 15] = { /* code 0027 */
  X_X____X,
  _X____X_,
  _X___X_X,
  XXXXXXXX,
  _XXXXXX_,
  X___X_X_,
  X_____X_,
  X_X_XXX_,
  XX__X__X,
  __X___XX,
  X__XXXX_,
  X_X__X_X,
  XX__X___,
  XX__XX_X,
  ____X___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0028[ 15] = { /* code 0028 */
  X____X__,
  ____XX_X,
  _X___XXX,
  ___X_XX_,
  _XXXXX_X,
  _XX_X_X_,
  __XXX___,
  X_X__XXX,
  _XX__XX_,
  XX_X_X__,
  X__XXX__,
  X_X_____,
  ___XX__X,
  XX__X_XX,
  XX_XXXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0029[ 15] = { /* code 0029 */
  XXX____X,
  XXX_XX__,
  X__X_XXX,
  _X__XXXX,
  __XXXX_X,
  X_____XX,
  _XX__X_X,
  _XX___XX,
  __XX__X_,
  _X__XXX_,
  __X_XXX_,
  X_X__X__,
  ____X_XX,
  __X__XX_,
  _XX_X___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_002A[ 15] = { /* code 002A */
  X_XXXX_X,
  _XX__X__,
  X__XX_X_,
  ___X_X_X,
  XXX_XXXX,
  ___XXXX_,
  _______X,
  __X__X__,
  ___X___X,
  __XX____,
  X_XXXXXX,
  __XXX__X,
  _X____X_,
  __X_XX__,
  ___XX_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_002B[ 15] = { /* code 002B */
  __X_X_X_,
  ____XXX_,
  _____X_X,
  X_XXX_XX,
  X___XXXX,
  _XX__X_X,
  X_XX__X_,
  _XXXXXXX,
  X_X_X_XX,
  _X__XX__,
  XXX_X___,
  XX_X_X__,
  XXX__XXX,
  _X_XX_X_,
  XXX_XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_002C[ 15] = { /* code 002C */
  __X___XX,
  _X_XX__X,
  _XX_X_XX,
  ______XX,
  XXX_XXXX,
  __X___XX,
  XX_X_XX_,
  _X___X_X,
  _XXXXX_X,
  XXXXX__X,
  XX_XXX__,
  X___X___,
  ___X___X,
  XXXXX_X_,
  X__X_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_002D[ 15] = { /* code 002D */
  XX_XX___,
  X__XX_XX,
  ___XX_X_,
  _X_X_X__,
  _XX___X_,
  ___X_XX_,
  X_XXXX_X,
  _____X__,
  XXXXX__X,
  _____XXX,
  XXX__XX_,
  XX_X___X,
  _XXX___X,
  __XX_X_X,
  _X_X__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_002E[ 15] = { /* code 002E */
  X___XXX_,
  _X_XX_XX,
  X_X_____,
  X_X_X_XX,
  __XXX__X,
  XX_X__X_,
  XXX_X__X,
  __XXX__X,
  XXXX_XXX,
  ____X_X_,
  X____X__,
  XXXX_XXX,
  _XXX_XXX,
  X__X__X_,
  _X_____X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_002F[ 15] = { /* code 002F */
  _X_X_XX_,
  _XX_X__X,
  XXX_X__X,
  __XX_X__,
  X_X_X_XX,
  XXXX__X_,
  __X_X_XX,
  _X______,
  XXX___XX,
  __X_XX__,
  XXX___X_,
  _XXXX_XX,
  _X_XX___,
  XXXXX___,
  _X__XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0030[ 15] = { /* code 0030 */
  __XXXXXX,
  X_XXX___,
  _X_XX__X,
  __XX__XX,
  __X___XX,
  X___X_X_,
  __XXXXXX,
  X_XX_X_X,
  X__X_X__,
  ____XX_X,
  X_XXXX_X,
  X_XXX__X,
  XXXXX___,
  __XXX___,
  _X__X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0031[ 15] = { /* code 0031 */
  _______X,
  XXX_X_X_,
  X__X_XXX,
  X_XXXXX_,
  _X__XX_X,
  __XX_XXX,
  XX__X_X_,
  X_X___X_,
  XX__XXXX,
  _XX_XX_X,
  XXXX__XX,
  __XX_X_X,
  X_X__X_X,
  X____XXX,
  ___X_XX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0032[ 15] = { /* code 0032 */
  ___X_XXX,
  XX_XXXXX,
  XX______,
  _XXXXX_X,
  XX_X_XXX,
  X____XXX,
  __X__X__,
  __XXX_X_,
  XX__XXX_,
  XX_XX__X,
  X__X__XX,
  _____XXX,
  X__XXX__,
  XXXX__XX,
  X____XX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0033[ 15] = { /* code 0033 */
  _XX__XX_,
  XXX_XXXX,
  X_XXX__X,
  __XXX_X_,
  _XXXX___,
  X_XXX___,
  X_XX___X,
  X_XX_X__,
  _XXXX_X_,
  _XXX_X__,
  X___X___,
  __XXXX__,
  _X_XXX_X,
  ___X_X__,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0034[ 15] = { /* code 0034 */
  XXXXX_X_,
  X__XX__X,
  __X__XX_,
  _X___X_X,
  _X______,
  X__XX___,
  X_X__X__,
  __XX____,
  X_X__XXX,
  _X__X_XX,
  X__X_X__,
  ___XXXX_,
  _XX_X_XX,
  ___XXX_X,
  X_XX_X__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0035[ 15] = { /* code 0035 */
  XXXXXX__,
  _XXXXXX_,
  _XX_X__X,
  X____X__,
  _XX__XXX,
  X__X___X,
  X___X__X,
  _XX___X_,
  ___X___X,
  __XX__X_,
  _X_____X,
  __X__XX_,
  X_X__X_X,
  __XXX_X_,
  _X__XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0036[ 15] = { /* code 0036 */
  XXXXXXX_,
  _XXX_X__,
  X_____X_,
  XX___XXX,
  X_X_X_XX,
  _XXXXXX_,
  X_XXX_X_,
  _X_X__XX,
  _XXX__X_,
  XX_X____,
  __XX_X_X,
  XX__XXXX,
  _X_X__X_,
  __XXX_XX,
  _XX_XX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0037[ 15] = { /* code 0037 */
  __X_X_XX,
  X___XX_X,
  X_X__XXX,
  ______X_,
  X_X__XXX,
  ___XX__X,
  _X_XXXXX,
  _XX_X__X,
  _X___X__,
  X__X_XXX,
  X_X__X_X,
  __XX___X,
  X______X,
  ______X_,
  XX____X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0038[ 15] = { /* code 0038 */
  _X___XXX,
  _X_X__XX,
  XXXX_XXX,
  ___XX_XX,
  _XXXXXX_,
  ____X___,
  ________,
  XXX__XX_,
  __XX__XX,
  X_XX_XX_,
  X_X_XXXX,
  _XX_XX__,
  __XXX_X_,
  __XXXXX_,
  _X____X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0039[ 15] = { /* code 0039 */
  _X_XX_X_,
  ___XX__X,
  _XXX__XX,
  XX__X___,
  XXX__X__,
  _XXXXXX_,
  XX_XX_X_,
  __XX____,
  XX__XX__,
  XXX_XXXX,
  X_X__XXX,
  _X_____X,
  XXXX____,
  X_XX__X_,
  X_XX____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_003A[ 15] = { /* code 003A */
  XX_X____,
  ___X__X_,
  XX______,
  _XX____X,
  XX_X_XXX,
  ____X___,
  ____X_X_,
  _____X__,
  _XX_XX__,
  _X_X____,
  XX_____X,
  _X__XXXX,
  __XXX__X,
  _XX_X___,
  X_XXX__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_003B[ 15] = { /* code 003B */
  ____XX__,
  X_XX_X__,
  ___X_X__,
  ___X_X_X,
  _X___X_X,
  XXX___X_,
  _XXXXXXX,
  X___XXXX,
  _X_X_X__,
  X__XXX__,
  _X_X_X__,
  X____X__,
  _XX_X_X_,
  XX_XXXX_,
  _X_X_X__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_003C[ 15] = { /* code 003C */
  __XX_X_X,
  _X______,
  X___X_X_,
  _XXX_XXX,
  X_XXXX__,
  _XXXX_XX,
  XXX_XXX_,
  _X____X_,
  _XXX__X_,
  XX_XX_XX,
  XX_X___X,
  X__XX__X,
  XX__X__X,
  X___X_X_,
  XX_XXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_003D[ 15] = { /* code 003D */
  X__XX__X,
  __XXX_X_,
  X_X_XX_X,
  XXX__XX_,
  XXXX___X,
  _XX___X_,
  _X_XXXXX,
  XX__X_XX,
  __XX___X,
  XXXX__XX,
  ___XX_XX,
  _XXX_XXX,
  _XXXXXX_,
  ___XXX__,
  XX__XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_003E[ 15] = { /* code 003E */
  ___XX___,
  X_X_XX__,
  __XX_XX_,
  _XX____X,
  _X__XX_X,
  ___XX___,
  X_X_X_XX,
  _X__XXXX,
  X___XXXX,
  ___XX__X,
  X___XXX_,
  X__X_X_X,
  XX_XX___,
  X_____XX,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_003F[ 15] = { /* code 003F */
  __X____X,
  ________,
  __X_XX_X,
  __XXXX_X,
  XX_XXX_X,
  X_X___X_,
  X_XX_XX_,
  _XX_X_XX,
  _X_XX_XX,
  XXX_X_XX,
  _X_XX_X_,
  X___XXXX,
  X____X_X,
  _XX_X_X_,
  XXX____X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0040[ 15] = { /* code 0040 */
  XXXXXXX_,
  __X__XX_,
  XXX_XXX_,
  ____X___,
  X_XX_X_X,
  XX_X__XX,
  _XXXXX_X,
  XX_XXX_X,
  XX__X_X_,
  _____X_X,
  X____X_X,
  X__X_XX_,
  XXXX__X_,
  ___XX_X_,
  _XXX_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0041[ 15] = { /* code 0041 */
  __XX__XX,
  X_XX_XX_,
  XXX__X__,
  XX_X_XX_,
  XX__X__X,
  X_XXXXX_,
  _XX_XX__,
  __XX____,
  XX_XX_X_,
  X__XXX_X,
  _XX____X,
  X_XX__X_,
  _X_____X,
  _XXX_XXX,
  XX__X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0042[ 15] = { /* code 0042 */
  XX__X_XX,
  _XXX___X,
  _XX__XXX,
  XXXX___X,
  __XX__XX,
  X_XXXXXX,
  __XXXXX_,
  __X___X_,
  __X_X_XX,
  X_XXX_XX,
  XX_X_X__,
  ___X__XX,
  X_X_XX__,
  XX___X_X,
  X___X_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0043[ 15] = { /* code 0043 */
  _XX__X__,
  X____XX_,
  X_X_X__X,
  _X__XX__,
  ____XX_X,
  _XX___XX,
  _XXX___X,
  __XXXX__,
  _X__XX_X,
  _XX_X_X_,
  __XXXXXX,
  X__XX___,
  _XXX_XXX,
  ___XX_XX,
  _____XX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0044[ 15] = { /* code 0044 */
  ____X_XX,
  _____X__,
  XXX__X__,
  _X__X_XX,
  X______X,
  ___XX___,
  X_X__X_X,
  XX__XXXX,
  __XXX___,
  ______X_,
  XXXXX__X,
  XX_XX_X_,
  X_XX___X,
  __X_X_XX,
  X__XXX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0045[ 15] = { /* code 0045 */
  X___XXX_,
  _XXX_XXX,
  _XX_X__X,
  X_X_X_XX,
  X_XX__X_,
  XX__XXXX,
  XXX_X_X_,
  X_XXXX_X,
  _X_X_X_X,
  __XXXXXX,
  X_XXXX_X,
  X___XXX_,
  _XX_XX__,
  XXX__XXX,
  _X__XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0046[ 15] = { /* code 0046 */
  __XXX__X,
  X__XXXX_,
  _XXX_XXX,
  ___XX___,
  ___XX__X,
  X__X__XX,
  ___XX__X,
  XXXXXX_X,
  _XX___X_,
  _XX___XX,
  X_XXX_XX,
  X_XX__XX,
  X_XXXX_X,
  ___X_X_X,
  __X_XX_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0047[ 15] = { /* code 0047 */
  __XXXX_X,
  XXXX_X_X,
  X_X___X_,
  ____X__X,
  X_X__XXX,
  ________,
  ____XXX_,
  X_XX_XXX,
  __XX_XXX,
  _XXXX_XX,
  X_X_____,
  X_XXX___,
  X___XXX_,
  XX_XXX_X,
  _X__X__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0048[ 15] = { /* code 0048 */
  XXX___XX,
  _X_XXX_X,
  __XX____,
  XX_X_X_X,
  X___X_XX,
  XX_X_XXX,
  ___X____,
  ________,
  _XXX__X_,
  __XX_XX_,
  X__XXX__,
  XXXX_XXX,
  __XXX___,
  XX___XXX,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0049[ 15] = { /* code 0049 */
  __XX___X,
  _X__X_X_,
  _____XXX,
  XXXXX__X,
  XXXXX__X,
  _XXX___X,
  XXXXX___,
  ____XX_X,
  X__XXX__,
  __XX___X,
  XX_X_XX_,
  X_X__X__,
  __XX_X__,
  __XXX_XX,
  ____XXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_004A[ 15] = { /* code 004A */
  XX__X_XX,
  __X__XXX,
  X__XXX__,
  ______XX,
  _X__X___,
  X__XX_X_,
  XXXX__X_,
  X__XX__X,
  X_XXXXXX,
  X_XXX_X_,
  XXX___X_,
  XX_X__XX,
  _X__X_X_,
  ___X_XXX,
  __XXXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_004B[ 15] = { /* code 004B */
  _X___XX_,
  _X_X_X_X,
  _XXX_X__,
  _X_XX_XX,
  ___X__X_,
  XX_XX_X_,
  _XXX__X_,
  X___XX_X,
  _XXX_XX_,
  XXXX____,
  X____X_X,
  XX_XX___,
  __XXX__X,
  ___X__X_,
  XX_XXX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_004C[ 15] = { /* code 004C */
  __XX____,
  _XXXXXXX,
  ___XX__X,
  XXX___X_,
  ____XX_X,
  X_XX__XX,
  _XX_X__X,
  X___X__X,
  X__XXXX_,
  __X__XX_,
  ___X_XX_,
  X_X__XX_,
  ____X___,
  ___X__X_,
  _X_X_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_004D[ 15] = { /* code 004D */
  X_X___X_,
  X_XXXX__,
  __XX_X__,
  X__X___X,
  ___X__XX,
  __XX_X_X,
  ___XX___,
  XXXX__XX,
  __X__X_X,
  XXX____X,
  __XXXX_X,
  XX_XX_XX,
  __XXXXXX,
  _X____X_,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_004E[ 15] = { /* code 004E */
  _X___XXX,
  XXX_X___,
  X_XX_XXX,
  XX__XXXX,
  _XXXXX_X,
  X____X_X,
  _XX_X_XX,
  X_XXXX_X,
  _X_____X,
  XXX___X_,
  _XX_X_X_,
  _XX_XX__,
  _XX_X_XX,
  ___XXX__,
  X__XX__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_004F[ 15] = { /* code 004F */
  X_X_XX_X,
  X______X,
  XX_X_XX_,
  __XXXXXX,
  X__X_X_X,
  XX____XX,
  XXXXX_X_,
  __X_____,
  __X___X_,
  X___X_XX,
  _XX_XXXX,
  X__X____,
  XXX___XX,
  _XXXXXXX,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0050[ 15] = { /* code 0050 */
  X_X___X_,
  _X_X_X_X,
  X___X__X,
  _X__XX_X,
  __XX_X__,
  __X_XXX_,
  X_X_XXXX,
  XXX__X_X,
  _XXX_XX_,
  X_X_XXXX,
  _X____X_,
  __XXXX__,
  ___X__X_,
  _XX___XX,
  XXX_X_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0051[ 15] = { /* code 0051 */
  X___XX_X,
  _XXX_XXX,
  _X__X___,
  _XX__XX_,
  _XXXXXX_,
  __XXX___,
  X_X__X_X,
  XXXX_X_X,
  X_X_XX__,
  _X__XXXX,
  _XXX_XX_,
  ____X_X_,
  _XX__X__,
  _XX_XX__,
  XXX_XXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0052[ 15] = { /* code 0052 */
  X_X__XX_,
  _X_X___X,
  __XXX__X,
  ___X_XX_,
  _X_XXXXX,
  X_XXXXXX,
  __XX_XX_,
  ___XXX__,
  X_XX___X,
  __X_X___,
  ___X__XX,
  X__X__XX,
  _XX_X_XX,
  __XX_XXX,
  _XX_XXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0053[ 15] = { /* code 0053 */
  X_XXXXXX,
  XX___X__,
  X__X_XXX,
  XXX_XX_X,
  _______X,
  X_XXX___,
  XX__X_X_,
  X_XXX_X_,
  _X_X_X__,
  __X__XX_,
  XX__X__X,
  XX_XX_XX,
  _X__XX__,
  __X___X_,
  __XXX_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0054[ 15] = { /* code 0054 */
  ___X____,
  __X_____,
  X___X_XX,
  _X__X_X_,
  _X_XX__X,
  XXXXX_XX,
  XXX_XX__,
  ___X__XX,
  X_XX___X,
  X_X_XX_X,
  _XXX___X,
  _X__XXXX,
  ____XX_X,
  X______X,
  ___X__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0055[ 15] = { /* code 0055 */
  _XX__X__,
  X__X__X_,
  XXXX____,
  _XXXX__X,
  __XXXXXX,
  X___XX__,
  XXX__XX_,
  __X_X_X_,
  __X_XXXX,
  __X_X__X,
  _XXX_X__,
  _XX___X_,
  __X__XX_,
  X_XXXX__,
  _X_XX_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0056[ 15] = { /* code 0056 */
  ____X__X,
  XXXXX___,
  _XX_X___,
  _X_XXXXX,
  __X_____,
  XX____X_,
  XX___XXX,
  ____X_X_,
  __XX__X_,
  X_X__XXX,
  __XX____,
  XX__XX_X,
  ______XX,
  __X_X_X_,
  _XX_XX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0057[ 15] = { /* code 0057 */
  X_XXX_XX,
  __XX__X_,
  _XX_XXXX,
  XXX_X_XX,
  _XXXXXX_,
  X__X____,
  XXX_____,
  ___X_XX_,
  __X_XXXX,
  XX_XXXXX,
  X__XX_XX,
  __X__X__,
  XX___X_X,
  X_XX____,
  _XX___X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0058[ 15] = { /* code 0058 */
  X_X__X_X,
  _X____X_,
  _XX_X___,
  XX____XX,
  X__X_X__,
  XX_X___X,
  ____XX_X,
  _XXX____,
  __X_XXX_,
  XX___X_X,
  XXX__XXX,
  XXXX_XXX,
  __XX__XX,
  _XXXXX__,
  _X_X_X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0059[ 15] = { /* code 0059 */
  X_X_XX__,
  XXXXX_XX,
  XXX_XXXX,
  __XXXXX_,
  __X____X,
  X__X_XXX,
  __X____X,
  X__XXXXX,
  _XXX__X_,
  XXXX_XX_,
  XX__X_X_,
  _______X,
  X__X__XX,
  X_X__XXX,
  X_XX_XX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_005A[ 15] = { /* code 005A */
  X_X_XXX_,
  _X___XXX,
  XX_X___X,
  _XX__X__,
  _XXX____,
  X___X__X,
  XXX_X___,
  X__XXXXX,
  XX_X_X__,
  _XX_X___,
  X_XXXX__,
  __X_____,
  __X____X,
  _X_X__X_,
  X_XX_X__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_005B[ 15] = { /* code 005B */
  _X__X___,
  XX___X_X,
  XX___X_X,
  X__X_XXX,
  XXX__X_X,
  ___X_X_X,
  XXXXX_X_,
  _XX_X__X,
  XXX_XXXX,
  __XX_XX_,
  _X__X_X_,
  _XXXX__X,
  __XX___X,
  XX___XX_,
  _XX__XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_005C[ 15] = { /* code 005C */
  __X__X__,
  __XX_XX_,
  XX__XXX_,
  __X__X__,
  XX_X_XX_,
  _XXXXXX_,
  _X_XX__X,
  X____XX_,
  X__X_X__,
  X_______,
  _XXXX_XX,
  XXXX_XXX,
  _X_X_XX_,
  XXX_X__X,
  X__XXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_005D[ 15] = { /* code 005D */
  X_X__XX_,
  __XX_XXX,
  X___X__X,
  X_____X_,
  X__X__X_,
  X_______,
  XX_X__XX,
  XXXX_X__,
  XXXX___X,
  ___X___X,
  XXX_X_X_,
  ____X_XX,
  XX_X____,
  X______X,
  XXXX_X__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_005E[ 15] = { /* code 005E */
  _X_X____,
  XX_X__XX,
  __X___XX,
  XX___XXX,
  ___XXX__,
  XXX_X__X,
  X_X_X_XX,
  _XX_X___,
  _XXXX__X,
  _X_X_X_X,
  _XX_XX_X,
  _X___X__,
  _X_XXXX_,
  _X__XXXX,
  XX___XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_005F[ 15] = { /* code 005F */
  _X__XXX_,
  _X__X___,
  ____XXX_,
  __XX_X__,
  X_XXX_XX,
  _XXX____,
  XXXX_XXX,
  XXX_XX__,
  XX__X_XX,
  XX__XX__,
  X____XX_,
  _XX_XX_X,
  ___X_X__,
  XXX_X___,
  _X__X__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0060[ 15] = { /* code 0060 */
  ______XX,
  _X_XX__X,
  X_X_XXX_,
  __XX____,
  X_X____X,
  XXXX_XXX,
  _X__X_X_,
  X___XXXX,
  __X_XX_X,
  _X_X____,
  __XX__X_,
  ___XXXX_,
  ___X___X,
  ____X_XX,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0061[ 15] = { /* code 0061 */
  X__XXX_X,
  X_X_X__X,
  X_X__XXX,
  X__XXXX_,
  X_XXX_X_,
  X_XXX_X_,
  _X__X_X_,
  __X_XXX_,
  ___XX_XX,
  XXXXX_XX,
  XXXXXX_X,
  XX___X_X,
  X___XX_X,
  X__X___X,
  ___XX_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0062[ 15] = { /* code 0062 */
  XX___X_X,
  _XXXXXXX,
  _XXXX_X_,
  X__XX_X_,
  _XXXX_XX,
  X___XX__,
  __X___X_,
  _X_X_XX_,
  XX_XX_X_,
  XXX_X_X_,
  _X_X_X__,
  ______X_,
  ______XX,
  ______X_,
  _XX__X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0063[ 15] = { /* code 0063 */
  X__X_X_X,
  X_X_X___,
  X____XX_,
  ___X____,
  _XXX__X_,
  _X____XX,
  XX__XXXX,
  __XXX__X,
  _XX_X_X_,
  __X_XXX_,
  _X_XXX__,
  X_XXX_X_,
  XXX__XXX,
  XXX__X_X,
  _X___X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0064[ 15] = { /* code 0064 */
  XXX____X,
  XX_X_X_X,
  _X__X___,
  XXX__XXX,
  XXXXX___,
  _XXX_XXX,
  X_XXXX_X,
  X_X_X___,
  __X__X_X,
  __X__XX_,
  X_XXXX__,
  __X_XX_X,
  _X_X__XX,
  X_XXXX__,
  __X_X_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0065[ 15] = { /* code 0065 */
  _X__X__X,
  X__XXX_X,
  XX_XX_X_,
  _______X,
  __XXXXX_,
  XX_X__X_,
  X__XX__X,
  XXX__X_X,
  _XX_X_XX,
  __XXX_X_,
  XX_XX_XX,
  XXXXXX__,
  __XXXX_X,
  _____XX_,
  XXXX__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0066[ 15] = { /* code 0066 */
  X___XXX_,
  ___XX_X_,
  X__XXX__,
  X___X_X_,
  XXXX____,
  _X_XXX__,
  _____XXX,
  X__X_XX_,
  __X___X_,
  _X_XX___,
  X_X__XX_,
  X__X_X_X,
  _XX_XXX_,
  _X___X__,
  __X__XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0067[ 15] = { /* code 0067 */
  X_XXXX__,
  ______X_,
  __X___X_,
  XXX____X,
  ___X_X__,
  __X_XX_X,
  X_X_____,
  _XX_X_X_,
  _XXXXX__,
  X_XX__XX,
  XX_X__XX,
  X_XXXX_X,
  __X_X_XX,
  X___X_X_,
  XX_XX_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0068[ 15] = { /* code 0068 */
  _X_____X,
  XX_XX__X,
  X_XX_XXX,
  ___XX__X,
  _XX_____,
  X____X__,
  X__XXXXX,
  ____XXX_,
  X___XXXX,
  _X_XX__X,
  _X_X_X__,
  XX__XX_X,
  __X__X_X,
  X_XX_X_X,
  __XX___X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0069[ 15] = { /* code 0069 */
  ________,
  __X_X___,
  X_X___X_,
  _X___XX_,
  X_XX_X_X,
  X__XXX_X,
  __X_X__X,
  X__X_X__,
  X__X____,
  X_X_X__X,
  X_XXX__X,
  _XX_XX__,
  ___X_XXX,
  __XXXXX_,
  ____X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_006A[ 15] = { /* code 006A */
  _X_XX_X_,
  X__X_XX_,
  _XXXXX__,
  X_____XX,
  X_XX_XXX,
  _X____X_,
  ___XX___,
  _X__X___,
  __XX_XX_,
  X__X_XX_,
  _XXXXX_X,
  X_X_X___,
  X___X_X_,
  __X_X__X,
  __X_X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_006B[ 15] = { /* code 006B */
  _X___X__,
  __XX___X,
  __XX_XXX,
  _X_XXX_X,
  X__X____,
  XXX_XX_X,
  XXXXXXX_,
  _XX__X_X,
  XXX__XXX,
  _X_XX_XX,
  ____X_XX,
  _______X,
  _X_X__X_,
  X__XX_X_,
  X_X___XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_006C[ 15] = { /* code 006C */
  __XXXX_X,
  X_XX___X,
  _X_XXX__,
  X_XX___X,
  __X_X_X_,
  X__X_XXX,
  X__XXXX_,
  ____XX__,
  _XX__X__,
  ___X_XXX,
  __X_X_XX,
  __XXX___,
  XXXX_X__,
  _X___X_X,
  _X_XXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_006D[ 15] = { /* code 006D */
  ___X___X,
  X_X_X__X,
  _XXX____,
  XX____XX,
  XX_XX_X_,
  XX_X__XX,
  X___XX__,
  XX_X_X__,
  XXX__X__,
  ___XX___,
  XXX_X___,
  _XXXXXX_,
  X_____XX,
  _X_XXXXX,
  X__X_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_006E[ 15] = { /* code 006E */
  ___X_XXX,
  XX_X____,
  X_XXXXXX,
  XX_____X,
  X___XXX_,
  XX_X_X__,
  ____X_XX,
  X_X_XX_X,
  XXXXXXX_,
  X_X__XXX,
  X__XX___,
  X__XX__X,
  X___X___,
  X_X____X,
  X____XX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_006F[ 15] = { /* code 006F */
  X____XX_,
  XX_XX__X,
  X_XX_X_X,
  __X_X_XX,
  XXXX___X,
  X__X_X_X,
  X__XXX__,
  X_X___X_,
  X_XXXXX_,
  XXXX_X__,
  X_X_X_XX,
  _XX__X__,
  __XX_XX_,
  XX___XXX,
  X_XXX__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0070[ 15] = { /* code 0070 */
  XXXXXX__,
  __X_XXX_,
  XX_____X,
  _XXXXX__,
  __XXX___,
  _X______,
  XX_X__X_,
  ___X____,
  _X_X_X__,
  X_XXX_XX,
  XX_X_X_X,
  XXXX_X__,
  XXX_____,
  XX_X_XX_,
  _XX__X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0071[ 15] = { /* code 0071 */
  X_XX__XX,
  ____XXX_,
  __X_X_XX,
  __X__XX_,
  _X_____X,
  __X_X___,
  X_____XX,
  _X___X_X,
  XXXXXX_X,
  X_X__XXX,
  XXX_____,
  X_XXXX_X,
  XXXXX___,
  X__XXXX_,
  _XXXXX_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0072[ 15] = { /* code 0072 */
  XXX_X___,
  _XX_XXX_,
  __X__X__,
  XX__X__X,
  ___X_XXX,
  XX__X___,
  __X_X_XX,
  __XX____,
  XXXX____,
  _XXXX_XX,
  XXXX____,
  X_____X_,
  XX__XX__,
  XXXXX_XX,
  X__XXX_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0073[ 15] = { /* code 0073 */
  _XX_XX__,
  _X__X___,
  ____X_XX,
  XXXX___X,
  XXX_XXX_,
  XXXX____,
  XXXX_X__,
  X_X_XXXX,
  __XX__X_,
  _X____XX,
  ___XX_X_,
  XX_XX__X,
  XXXX____,
  X__X_X_X,
  _XXX__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0074[ 15] = { /* code 0074 */
  XXX___X_,
  _XXX__XX,
  _______X,
  XXXX_XX_,
  X____XX_,
  ________,
  XXX_XX__,
  __X_X___,
  X_X_____,
  X______X,
  __X___XX,
  __XXXXX_,
  X_X_XXXX,
  X____X__,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0075[ 15] = { /* code 0075 */
  X_X_____,
  _XX____X,
  __X___XX,
  XX_X__XX,
  X__X___X,
  _XXX___X,
  _____X_X,
  __X___X_,
  _X_XXX__,
  __X_XX__,
  XX_X__X_,
  X_XX___X,
  _X_X_XXX,
  XX_XXX__,
  XX_XX_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0076[ 15] = { /* code 0076 */
  X_XX_XX_,
  ___XX__X,
  X__XXXX_,
  X_X_XXX_,
  X___XX__,
  _X__XX__,
  _X_XXXXX,
  XXX__X_X,
  __XXX_X_,
  X__XXX_X,
  __X__XXX,
  X_X____X,
  _XXX_X_X,
  XX__X___,
  X___X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0077[ 15] = { /* code 0077 */
  X__XXXX_,
  _____X_X,
  XXX_X_X_,
  ___X_X_X,
  XXX_XXXX,
  XXXXXXX_,
  X___X_X_,
  X___X_XX,
  XXXX____,
  X_XXXXXX,
  ____X___,
  __X_XXXX,
  XXX___XX,
  XXX_XX_X,
  __XX__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0078[ 15] = { /* code 0078 */
  X_X___X_,
  XX__XX__,
  X___XXXX,
  _____XX_,
  _XX_XXX_,
  XXX_____,
  X_XX_XXX,
  _X_XXX__,
  XXXX___X,
  __X_XXX_,
  X_XXXXXX,
  X___X__X,
  __X__X__,
  _X_X__X_,
  X_X__X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_0079[ 15] = { /* code 0079 */
  X_X__X_X,
  XX_XXXX_,
  X_X_X_X_,
  ____X__X,
  _XX____X,
  _XX_XX_X,
  XXXX____,
  ___X_XXX,
  __XXXXX_,
  ____X___,
  __XXX__X,
  _X_XX__X,
  X_X_XX__,
  X_X_X___,
  _X_X__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_007A[ 15] = { /* code 007A */
  X_X_XXXX,
  XX_X_X__,
  __XX__XX,
  XX_X_X__,
  XX___XXX,
  _X___X_X,
  ___X__XX,
  _X_XXXXX,
  ___XX_X_,
  XX___XXX,
  X_X____X,
  XX__X_XX,
  _XX____X,
  _XX____X,
  X_X__XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_007B[ 15] = { /* code 007B */
  _XX___X_,
  X_____XX,
  XXX___X_,
  XXXX_X_X,
  XXXX____,
  __X_X_X_,
  __XX_XX_,
  X__X___X,
  __XXXXX_,
  __X_X_XX,
  XXX__X__,
  _XX_____,
  XX_XXXXX,
  X___XXX_,
  _X_XXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_007C[ 15] = { /* code 007C */
  __X_X_X_,
  __XX__X_,
  __XXXX_X,
  XX_X_X_X,
  _X_X_X__,
  XXX___X_,
  XXX__XX_,
  ___XXXX_,
  _XX_XXXX,
  ___X___X,
  _XXXXXX_,
  _XXXXX_X,
  ____X_X_,
  __XX_XXX,
  X__X_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_007D[ 15] = { /* code 007D */
  XX_X_X_X,
  __X____X,
  XX____XX,
  XX_X___X,
  XX____XX,
  X_X_____,
  XX____X_,
  ___X__XX,
  _X_XXX_X,
  XXX_XX_X,
  _XX____X,
  X_X_X___,
  _X_XXX_X,
  XXXXXXX_,
  ___X_XX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_007E[ 15] = { /* code 007E */
  _X_X____,
  XXXX__XX,
  __X_X__X,
  X______X,
  _X__X_X_,
  X_XXX_X_,
  _X__X___,
  XXXXX___,
  XX__XXX_,
  X__X___X,
  X__X_XXX,
  X__XXXXX,
  XXX__XXX,
  _XX____X,
  XX_XX_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_007F[ 15] = { /* code 007F */
  XXXX_X__,
  _X______,
  __XX___X,
  __X___X_,
  __XX_XXX,
  ____XX_X,
  __X__XXX,
  _____XX_,
  _X_XXXX_,
  _XXXX_XX,
  _X___X_X,
  X__X_X_X,
  _XX_XXXX,
  _____X_X,
  _X__XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A0[ 15] = { /* code 00A0 */
  ___XXXXX,
  X_XX__XX,
  XXX__XX_,
  _X___XXX,
  X_X__X__,
  X_XX___X,
  X__XX_X_,
  XXXXXXX_,
  __X_XXXX,
  XX__XX__,
  XXXXXX_X,
  XX_XX__X,
  XXX_X_XX,
  XX______,
  XX__X___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A1[ 15] = { /* code 00A1 */
  XX_X__XX,
  _XXX____,
  _X_XX__X,
  _X_XXXX_,
  X____X__,
  X_X___XX,
  _____XX_,
  _X__XXXX,
  _XX_X___,
  _X_XX_XX,
  _X_XXX__,
  _XXXX_X_,
  ____X_X_,
  _XX_X___,
  X_X___X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A2[ 15] = { /* code 00A2 */
  _XX_XX__,
  XX_X_XXX,
  X____X_X,
  _X_XX___,
  X_X___XX,
  __XX_XXX,
  __X__XXX,
  _XXX____,
  XX_XXX__,
  ____X__X,
  __XX__X_,
  X____XX_,
  X_XX_X__,
  X_____X_,
  X__X_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A3[ 15] = { /* code 00A3 */
  ____XX__,
  _XX____X,
  ____X_X_,
  X_X_X__X,
  X_XXX___,
  X__XX_XX,
  X_X_XX__,
  __X__X__,
  XX___X__,
  XXXXXX_X,
  ____XX_X,
  _XXXXX__,
  _XX___X_,
  _X_X__X_,
  X__XX__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A4[ 15] = { /* code 00A4 */
  ___X_X__,
  XX_XXX__,
  XX_X__XX,
  _XXXX__X,
  _XX_XX_X,
  ____XX_X,
  _XXXXX_X,
  X__X__XX,
  __X__X__,
  _X______,
  XX__XXX_,
  _XX_XX__,
  _X_X__X_,
  X__XXX__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A5[ 15] = { /* code 00A5 */
  X____X_X,
  _XX_XXXX,
  ______XX,
  X___XX__,
  X_______,
  ____XXXX,
  XXXX_XXX,
  _XX_XX_X,
  _X_XX___,
  __X__XXX,
  XXXX_X_X,
  X_X_X__X,
  XXX_X_X_,
  __X__X__,
  _XXX____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A6[ 15] = { /* code 00A6 */
  _XX_X__X,
  XX_X__X_,
  _XX_XXX_,
  _X_X__XX,
  XX_XXXX_,
  _XX___X_,
  XXXXXXX_,
  XXX_X___,
  X_X_X_X_,
  __X__XX_,
  X_X___XX,
  X_XX___X,
  ___X__X_,
  __X__X__,
  XX___X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A7[ 15] = { /* code 00A7 */
  X_X_X___,
  __XXXX_X,
  XXXXXXX_,
  ___X__XX,
  XX_XXX_X,
  X__X_XXX,
  X_XXX___,
  _X___X_X,
  ___X_XX_,
  X_XX__XX,
  XX__XX__,
  X_X__X__,
  _X_X_X_X,
  _XXXX_XX,
  X_X_X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A8[ 15] = { /* code 00A8 */
  ___X__XX,
  _XX_XX__,
  ____X___,
  X__XXX__,
  X__X__X_,
  ___XXX_X,
  _XXX_XXX,
  XXXX__X_,
  X__X_XX_,
  ______XX,
  ___XXX__,
  XXX_XXX_,
  __X_____,
  X__X___X,
  _XXX____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00A9[ 15] = { /* code 00A9 */
  XX____XX,
  X_X_X___,
  X_XX__X_,
  ___X___X,
  _XXX_X__,
  _XXXXXX_,
  X__X__X_,
  __XXX_X_,
  __X_XXXX,
  XXXXXX__,
  XX_XX_XX,
  __X__X__,
  __X_XX_X,
  ____X_X_,
  __X__X__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00AA[ 15] = { /* code 00AA */
  __XXXX__,
  XX___X_X,
  _X_X_XX_,
  _X_XXXX_,
  ________,
  X____XXX,
  XXXXXXX_,
  X_____X_,
  X___X___,
  _X__X___,
  ________,
  XX___XX_,
  XX____X_,
  _X_XX_X_,
  __X___X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00AB[ 15] = { /* code 00AB */
  __X___X_,
  X_X__XX_,
  X_X__XX_,
  X_XXXXX_,
  X____X__,
  _X__X_X_,
  __XXX_XX,
  X___X_X_,
  ___XXX__,
  ___XXXXX,
  X_XX_X_X,
  __XXXXX_,
  __X_X_X_,
  XXX_X_X_,
  ___X__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00AC[ 15] = { /* code 00AC */
  ____X__X,
  X__X_X__,
  ____XXX_,
  ________,
  XXX_X___,
  ________,
  __X_X__X,
  XX__XX__,
  X___XXX_,
  XX__XX__,
  X_X_X__X,
  X__X____,
  XXX_X__X,
  __X_XXXX,
  _____XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00AD[ 15] = { /* code 00AD */
  __X_XXX_,
  X_X__X_X,
  XX_X__X_,
  X_XX_XX_,
  XXX_X__X,
  XX_X__XX,
  X__XXX__,
  _XX_X_XX,
  _XX_X___,
  XXXX__X_,
  _XX____X,
  XXX__X__,
  X___XX_X,
  X____XX_,
  XX___X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00AE[ 15] = { /* code 00AE */
  ___XXXXX,
  X_XX_XXX,
  X___X_X_,
  X_XX_X_X,
  XX_X__X_,
  __XX_X__,
  X_X_XX_X,
  __XX____,
  ____X__X,
  __XXX_XX,
  _XXX__XX,
  _______X,
  _____X__,
  X___XXXX,
  _XXX__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00AF[ 15] = { /* code 00AF */
  XXX_X_X_,
  XX_XX__X,
  X___X_XX,
  __X__XX_,
  XXXX__XX,
  _XX__X__,
  XX__XX_X,
  XX___X__,
  X__XX_X_,
  _X____XX,
  _XX___XX,
  X___XXX_,
  _XX_XXXX,
  XXX_X__X,
  ___XXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B0[ 15] = { /* code 00B0 */
  _X_____X,
  ________,
  XX__X__X,
  _X___XXX,
  ____XX_X,
  _X___XXX,
  X__X____,
  _X_X__XX,
  X__X_X_X,
  __XXX_X_,
  _XXX__X_,
  __XX____,
  ____XXXX,
  ___XXXXX,
  ____XX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B1[ 15] = { /* code 00B1 */
  __XXXXXX,
  X__X___X,
  _X_X___X,
  _XX_XXX_,
  __XX__XX,
  __XX_X_X,
  _X___XXX,
  ______X_,
  __X_X_X_,
  X____X__,
  X_X_____,
  _X__X_X_,
  __XXX__X,
  _XXX__X_,
  X_X_____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B2[ 15] = { /* code 00B2 */
  _X_____X,
  X____XX_,
  XXXXX__X,
  X_X_X__X,
  _X_X_XXX,
  XXXX__XX,
  ____XXX_,
  _XXX_XX_,
  _X___XX_,
  ___XX_X_,
  XX_X__X_,
  __X_XX__,
  XXXX__XX,
  _XXXX_X_,
  _XXX_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B3[ 15] = { /* code 00B3 */
  XX_X___X,
  XXXX__XX,
  X_X__X_X,
  __X_X___,
  X_XX_X__,
  X_XXX___,
  XX_X_XXX,
  X_XXX_X_,
  __XX_XX_,
  _X_X____,
  _XX_X_XX,
  __XXX_XX,
  XXXX_X__,
  _XX_X_X_,
  XXXX_XX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B4[ 15] = { /* code 00B4 */
  ____X_X_,
  XXXXXXX_,
  XXX_XX__,
  X_XXX___,
  X_XX__X_,
  _XX_XXX_,
  X____X__,
  _X_X_XX_,
  X___XX_X,
  XXXX_XXX,
  _XXX_XX_,
  XXXXXX_X,
  XXX__XXX,
  ___X_X__,
  XX_XX_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B5[ 15] = { /* code 00B5 */
  _XX____X,
  X___X_XX,
  X__XXXX_,
  XX_XXXX_,
  X_XXXXX_,
  _XX_XXX_,
  _XXXXX_X,
  _XXX__XX,
  _XX___XX,
  __XXX__X,
  X_XX_X__,
  XX__XX_X,
  _____XXX,
  _XXXXXX_,
  XX__XXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B6[ 15] = { /* code 00B6 */
  ___X___X,
  XX___X_X,
  _XXX_XXX,
  _XXX_X_X,
  X__X_XXX,
  _XX_____,
  ______X_,
  X____XXX,
  _XX___X_,
  __X_XXX_,
  ____XXX_,
  X____XXX,
  __X__X__,
  X__XX__X,
  X_X_X__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B7[ 15] = { /* code 00B7 */
  ______X_,
  XXXX__X_,
  __X__XX_,
  XXXX_XXX,
  __X__X__,
  _XXX_XXX,
  _____XX_,
  XX___XXX,
  X__XX_X_,
  X_X__XXX,
  _XXX__XX,
  __XXX_XX,
  XX___X_X,
  X___XXXX,
  XX______};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B8[ 15] = { /* code 00B8 */
  ________,
  _X_XXX__,
  __XXX___,
  X___XXX_,
  X___X_XX,
  __XXX_XX,
  ___XX_X_,
  XX_X__XX,
  XX__X___,
  _XXX__X_,
  X_XXXXXX,
  X_X_X_X_,
  ____X___,
  __XX_XX_,
  XXX___X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00B9[ 15] = { /* code 00B9 */
  XX_X_XX_,
  ___XXX__,
  __XXX___,
  X____XX_,
  XXXXXX_X,
  X___XXXX,
  _XX_X_XX,
  X_X_X___,
  X__X____,
  _X_XXX_X,
  _X_X_XXX,
  ___X___X,
  X__XXX__,
  X_XXX___,
  _XXX_X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00BA[ 15] = { /* code 00BA */
  _XXXX__X,
  X_XX_X_X,
  ___X_X_X,
  _X_____X,
  __XXX___,
  X______X,
  XXXX___X,
  XXX__XX_,
  __XXX_XX,
  _X__X__X,
  _XXXXXXX,
  X_XXX__X,
  X_X_X__X,
  _X_XXXX_,
  X___X_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00BB[ 15] = { /* code 00BB */
  XX_X_XX_,
  X_XX__X_,
  __XX__XX,
  _X_X__XX,
  _XX_XX__,
  X___XX_X,
  XXXX_XXX,
  _XXX__XX,
  _XX__XXX,
  X___X__X,
  X_XXX___,
  X_XXXX_X,
  X_XX_XX_,
  _X__XXX_,
  __X_X___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00BC[ 15] = { /* code 00BC */
  __XXXXXX,
  _X_X_X__,
  __X_X__X,
  XX_X__X_,
  _XXX_X__,
  _XX___XX,
  ___X___X,
  _X_XX__X,
  X___XX_X,
  XXX_X___,
  X____X__,
  _X_____X,
  X_XX_XXX,
  _X_XXX__,
  _X_XXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00BD[ 15] = { /* code 00BD */
  XXX_X_XX,
  ________,
  XXX__X_X,
  __X_XX__,
  _X_X__XX,
  _XX___XX,
  _XX__XX_,
  X_X__X__,
  X__XX_X_,
  ____XXX_,
  X_XXX___,
  __X__X__,
  _XX___XX,
  __X__XX_,
  _X_XX__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00BE[ 15] = { /* code 00BE */
  X__XX___,
  XX__X___,
  __XXXX__,
  X_X__X__,
  __XXX_XX,
  ___XX_X_,
  _XX_X_X_,
  _XXXXX_X,
  XXX____X,
  ___X__X_,
  _XXX___X,
  __X__XXX,
  _XX_X__X,
  XXXXXXXX,
  ____XX_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00BF[ 15] = { /* code 00BF */
  X__XXX_X,
  X_______,
  _X____XX,
  _____XXX,
  _X_X_X_X,
  _X__XXXX,
  _X_X_X__,
  __X__X__,
  _X_XX___,
  X____X__,
  X___X__X,
  _XXXX_X_,
  XXXX_XX_,
  ____XXXX,
  XXXX__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C0[ 15] = { /* code 00C0 */
  XX___XX_,
  X___X___,
  _X_XXXXX,
  _XXXXX__,
  X_XXXXXX,
  X__X_X_X,
  XXXXXX_X,
  __XXXX_X,
  X___XXXX,
  _XX_XX_X,
  XX__X_X_,
  _____X_X,
  __X____X,
  _X_XX__X,
  _XX_____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C1[ 15] = { /* code 00C1 */
  _XX_XXX_,
  _X__XX__,
  _XXX__X_,
  _X___XX_,
  __XX_XXX,
  X____X__,
  __XX_X__,
  X__XX__X,
  __XXX__X,
  ___XX__X,
  _X__X___,
  XX__XX_X,
  _X____X_,
  X_X___X_,
  _XXXX__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C2[ 15] = { /* code 00C2 */
  XX_X__X_,
  _X__X__X,
  XX_XX___,
  __X__X_X,
  XXX___XX,
  _X__X__X,
  __XXX___,
  __XXXXXX,
  X___XX_X,
  _X_XX___,
  X__XX___,
  _X_X__XX,
  XX____XX,
  _X__XXX_,
  _X_XXX_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C3[ 15] = { /* code 00C3 */
  XX_X_XX_,
  XX__XXXX,
  _XXX_X__,
  XXXX_XX_,
  XX_X_XXX,
  XX_X__XX,
  X__X__XX,
  _____XXX,
  X_______,
  XX__X__X,
  XXXXXXX_,
  _X_XXX_X,
  _XXX__X_,
  XXXX_X_X,
  ___XXX_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C4[ 15] = { /* code 00C4 */
  XX_XXXX_,
  __X__XXX,
  _XXXXXXX,
  _X_X_XX_,
  __XX__XX,
  XX___XX_,
  __XX_X_X,
  X_X____X,
  __XXX_XX,
  XX__XXX_,
  _X_X__XX,
  ___X_X_X,
  XXXX_X__,
  _______X,
  XXX___XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C5[ 15] = { /* code 00C5 */
  __X__X__,
  X_X_____,
  X__XX___,
  XXXX_XX_,
  XX__XX__,
  __XX_XX_,
  ____XXX_,
  __X_XX_X,
  __X___XX,
  _______X,
  X_XX___X,
  XX_XX_XX,
  X___X_X_,
  XXX___X_,
  _XX__X__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C6[ 15] = { /* code 00C6 */
  XX_X_XX_,
  ___X_XXX,
  X_X___X_,
  XXX_X_X_,
  _X_X_XX_,
  XX__XXX_,
  X_X___XX,
  ____X_XX,
  XXX___X_,
  __XX_X_X,
  X_XXX__X,
  XXXXXXXX,
  _X_X___X,
  XXXX__XX,
  XXX___XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C7[ 15] = { /* code 00C7 */
  __XXXXXX,
  X___X_X_,
  X_XXX_XX,
  X__XX___,
  X____X__,
  ___XX_X_,
  ___X_XX_,
  X__XX__X,
  XXX_X__X,
  XXXXX_XX,
  XXX_XX__,
  X_____X_,
  _XXX__XX,
  __XXXX_X,
  XXX_XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C8[ 15] = { /* code 00C8 */
  X_XX__XX,
  _XXXXX__,
  XXXXXXXX,
  _X_XXX__,
  ___XX_X_,
  XXX__X__,
  XXX_____,
  _XXXXX__,
  _X__X__X,
  XXX_X_X_,
  __XXXX__,
  X__X___X,
  __XX_XX_,
  __XXXXXX,
  X____XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00C9[ 15] = { /* code 00C9 */
  X__X__X_,
  X___X_XX,
  __X_XXXX,
  X_XX_XX_,
  XXXXX___,
  XXX__X__,
  _X__X_XX,
  __XXX_XX,
  X____X_X,
  _X_____X,
  ________,
  __XX_X__,
  _X_XX___,
  ______XX,
  _X____X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00CA[ 15] = { /* code 00CA */
  _XX_XX_X,
  __X__X__,
  X__X_X_X,
  _X_XX_X_,
  X_XX_XXX,
  ____X_XX,
  _XX__XX_,
  ___XX_XX,
  X_X_X__X,
  _XX__X__,
  XX_XX___,
  __X__X_X,
  X__XX_XX,
  XXX__X_X,
  __XX_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00CB[ 15] = { /* code 00CB */
  ____XXX_,
  XXXX_XX_,
  XX_X_X_X,
  X__XXX__,
  __X__X_X,
  X_XX_X_X,
  XXX___XX,
  ___XX___,
  _____X_X,
  X_X__X__,
  X_XXX__X,
  XXX___XX,
  XX___X_X,
  X_X___X_,
  __X_X___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00CC[ 15] = { /* code 00CC */
  _____X__,
  X_XX__X_,
  X_XX__XX,
  _X_____X,
  XX__X___,
  ________,
  ___X_XX_,
  X_X_____,
  ___XX_XX,
  ___X_X_X,
  _____X__,
  XXXXXXXX,
  __XX_XX_,
  XX_X____,
  _X___XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00CD[ 15] = { /* code 00CD */
  _X__XX__,
  X_XX_X__,
  X_XXXXX_,
  X_X__X__,
  __XXX__X,
  _XXXX__X,
  ___X__XX,
  X__XXX__,
  X_X_X___,
  _XX_____,
  X__XX_X_,
  ____X__X,
  __X___XX,
  X_XXX___,
  __X_XXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00CE[ 15] = { /* code 00CE */
  _X_X_XXX,
  X___XX__,
  X____XXX,
  X__X__XX,
  X_XX___X,
  __X__XXX,
  XXX_XXXX,
  ___X_X__,
  __X_XXX_,
  XXXXX_X_,
  XXX___XX,
  XX_XX_X_,
  __X_XXXX,
  _____XXX,
  __X_XXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00CF[ 15] = { /* code 00CF */
  __XXX__X,
  X__X___X,
  X_XXX___,
  __XX__XX,
  XX_XXX_X,
  __X___X_,
  _XXXXX__,
  _XX__X_X,
  ____X_XX,
  XXXX_X__,
  XXX__XX_,
  ___XXX__,
  XX_X_X__,
  _XX_____,
  X__X__X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D0[ 15] = { /* code 00D0 */
  ___XX___,
  XXX_X_XX,
  X___X__X,
  __XXX__X,
  ___X_X__,
  __X___XX,
  _X___X_X,
  XXX_X_X_,
  X_XX__XX,
  X_X_XXX_,
  ____XX_X,
  XXXX___X,
  X__XXX_X,
  X____X__,
  X__X__X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D1[ 15] = { /* code 00D1 */
  X__X___X,
  XX__XX_X,
  XXXXXXX_,
  _XX__XX_,
  ____XX__,
  __XX____,
  _XX_XX_X,
  _XXX__X_,
  _X__X_XX,
  ______X_,
  __XXXX_X,
  XX_X_X_X,
  _XXX_X_X,
  XXX____X,
  ___XX_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D2[ 15] = { /* code 00D2 */
  XX__XXXX,
  X___X___,
  XX___XX_,
  _X_X_XX_,
  _X_XXXXX,
  XX_X___X,
  ___XX_XX,
  XX_X__X_,
  ___X_XXX,
  XX__XX_X,
  ___X_X__,
  X_XXXX__,
  _X___X__,
  X_X__XX_,
  XXX____X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D3[ 15] = { /* code 00D3 */
  X___X__X,
  _X_XX_XX,
  X_X_X_XX,
  _X_X_X_X,
  _X_X_XXX,
  XXX_X___,
  X_X_XX__,
  X_XX__X_,
  _X_XXX__,
  X_X_XX__,
  __X_X_X_,
  ___XX_XX,
  _XX__XXX,
  XX__XX_X,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D4[ 15] = { /* code 00D4 */
  X__X_X_X,
  __X__XXX,
  XX_X_XX_,
  ________,
  _XX_XXXX,
  X_XX_X_X,
  XX_XXX__,
  _XX__X_X,
  X__XX__X,
  XXXX____,
  _X___X__,
  X_X_XX_X,
  _X___X_X,
  X_______,
  _XX_XX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D5[ 15] = { /* code 00D5 */
  XXX_XX_X,
  ___X___X,
  _X___XXX,
  _XXX_X__,
  __X___X_,
  X_XX_XXX,
  X__X__X_,
  X_XXX_XX,
  XX_X__XX,
  __XX_X_X,
  X_XXX___,
  X___XXX_,
  XXX__X__,
  _XX_XX_X,
  _XXX__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D6[ 15] = { /* code 00D6 */
  XXX__XX_,
  _X_____X,
  XXX_XX_X,
  XXX_X___,
  _XXXX_XX,
  X_XXXXX_,
  X_XXXX_X,
  XXXXX___,
  X_X___X_,
  _XXX___X,
  ___XX_X_,
  _X_____X,
  XX____X_,
  XXX_X___,
  _XX_X_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D7[ 15] = { /* code 00D7 */
  X_____X_,
  _X_XXX_X,
  _XX__XX_,
  _XX_XX_X,
  ___XX___,
  XX_____X,
  X_XX____,
  __XXXXX_,
  XXXXX__X,
  _XX_XXXX,
  _X_X_XXX,
  __XX_XX_,
  X___X__X,
  XX_XX_X_,
  X______X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D8[ 15] = { /* code 00D8 */
  _XX_X___,
  _X_XX__X,
  _____XXX,
  _X__X_XX,
  ___X___X,
  XXX__XX_,
  X__XX___,
  _XX_XX_X,
  ___X_X_X,
  ___XX__X,
  _XXX_XXX,
  X__X_X_X,
  ___XXX_X,
  __XX____,
  X_XX__X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00D9[ 15] = { /* code 00D9 */
  _____XXX,
  __XXXXX_,
  X__XXX__,
  _XXX___X,
  __XXX_X_,
  ___X____,
  X__X_XX_,
  XXX_X___,
  X___X___,
  XX______,
  ____XX__,
  X__X___X,
  X_X__XXX,
  X_XX_X_X,
  ___XX_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00DA[ 15] = { /* code 00DA */
  ____X___,
  XXX__XX_,
  X__X_XXX,
  _X___XXX,
  ____XXXX,
  ______X_,
  _XX_XX_X,
  __XXXX_X,
  X_X__X_X,
  _XXX_X_X,
  _X___XX_,
  XX_X_XX_,
  X_X____X,
  __X_XX__,
  X__XXXX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00DB[ 15] = { /* code 00DB */
  X_XX____,
  _XX_XX__,
  _X____X_,
  ___X__XX,
  X_X_XX__,
  __XXX_X_,
  _XXXX__X,
  XXX_X___,
  XX_XXX__,
  _____X_X,
  ___X_XXX,
  XX____X_,
  XX__X__X,
  _X___XX_,
  ___X__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00DC[ 15] = { /* code 00DC */
  __XXX_X_,
  _XXXX_X_,
  _X_XX_X_,
  __X_X_X_,
  X__X__XX,
  _X_X_XXX,
  __XX_XX_,
  X__X_X_X,
  ___X_X_X,
  _XXX__XX,
  __X_X__X,
  XX__XXXX,
  XXX_XXX_,
  __XX_XXX,
  __XXXXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00DD[ 15] = { /* code 00DD */
  XX__X___,
  ___XXX_X,
  XX_____X,
  __X_XXX_,
  __XX_X__,
  _X___X_X,
  XXXX__X_,
  ___XX_XX,
  _X____X_,
  X__X_X__,
  __X___XX,
  X___XXXX,
  X___XX_X,
  __XXX_XX,
  __X___X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00DE[ 15] = { /* code 00DE */
  XX______,
  X_XX_XXX,
  __XXX__X,
  XX__X_X_,
  XXXXXX__,
  _X__XXXX,
  XXX_XX__,
  _XX_XX_X,
  ___X_XX_,
  XX_XXXX_,
  XXX_X__X,
  _XXXXXX_,
  ________,
  _X_X_XX_,
  ___X____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00DF[ 15] = { /* code 00DF */
  XX_XX_X_,
  XX_XX___,
  XXXXXX__,
  ___XX_X_,
  _XXX___X,
  __XXX_X_,
  XX_X_X_X,
  XX___X__,
  XX______,
  __XX__XX,
  ____XX_X,
  XXX_X___,
  __X_XXXX,
  X_XX__X_,
  X_XXXX_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E0[ 15] = { /* code 00E0 */
  X_XXX__X,
  XXX__XXX,
  ___XXXXX,
  XX__XXX_,
  X_XXX_X_,
  __X_X_XX,
  X_X__X_X,
  __X_XX__,
  XXX_XX_X,
  _XXXX_XX,
  _XXXXX_X,
  X____X_X,
  X__X_X__,
  X_X_____,
  XXX_XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E1[ 15] = { /* code 00E1 */
  _X______,
  X__X___X,
  ____X__X,
  ____XXX_,
  _X__XX__,
  X__XX__X,
  _X_X__X_,
  XX__X___,
  X__XX_X_,
  X_XXX_X_,
  XX_XXX_X,
  ____X_X_,
  X____XXX,
  ___X____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E2[ 15] = { /* code 00E2 */
  ___XX_XX,
  _XX__XXX,
  _X_____X,
  ____XXX_,
  XXX_X_XX,
  _XX_X_X_,
  __XXX___,
  ___XX_XX,
  _XXX__XX,
  X_X_X__X,
  X__XX__X,
  _X____XX,
  _XXXXX__,
  X___X_XX,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E3[ 15] = { /* code 00E3 */
  XXX_XXXX,
  XX_X_XX_,
  XXXXX___,
  _XX_X_XX,
  X_X__X__,
  XX_X__XX,
  X_X____X,
  ___XX_XX,
  X_X___X_,
  X__XX_X_,
  X_XXXXX_,
  X_X_XXXX,
  XX__XXXX,
  _X__X_X_,
  XX_XXX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E4[ 15] = { /* code 00E4 */
  _XX_XX__,
  XXXXXXX_,
  _XXX_X__,
  XXXXXXX_,
  XX__XXX_,
  X_X_X__X,
  __XXXX_X,
  XX_XXXX_,
  __XXXXXX,
  X_X_X_X_,
  __XX___X,
  XX___XXX,
  X__X_XX_,
  _____X_X,
  _X_X_X__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E5[ 15] = { /* code 00E5 */
  XXXXX___,
  ___X__X_,
  _XX____X,
  _X_XX_XX,
  _XX___X_,
  XXX_X___,
  _X_____X,
  _XX__X_X,
  __XX_XXX,
  ___X____,
  X__X__XX,
  _X_XXXX_,
  XX_XX_XX,
  XX______,
  XXX__X_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E6[ 15] = { /* code 00E6 */
  XXX____X,
  X__XX_XX,
  ________,
  __XX___X,
  XXX____X,
  _X______,
  __XXXXX_,
  _XXX____,
  X_X___X_,
  ____X_X_,
  X_XXXX__,
  XX__X___,
  _____X_X,
  X_____X_,
  _XX___XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E7[ 15] = { /* code 00E7 */
  ___XXXXX,
  _XX_XX_X,
  _XXX__XX,
  _XXXXXX_,
  ___XXXX_,
  XXXXX___,
  _X_X___X,
  X_______,
  X___X_X_,
  X_X___XX,
  X__X_XXX,
  X__X_XXX,
  __XX_XXX,
  _X___X__,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E8[ 15] = { /* code 00E8 */
  XX_X_X__,
  XXXX___X,
  XX__X___,
  X_______,
  XXXX_X_X,
  _XXXXXXX,
  XX__X___,
  _X_X____,
  __XX_X_X,
  X__X_X_X,
  _XX__X__,
  X_X___XX,
  __XXXXXX,
  _XXXX__X,
  XX_X_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00E9[ 15] = { /* code 00E9 */
  XXXX_X_X,
  _XX_XX_X,
  X_X_X_XX,
  ____X__X,
  __XXXX__,
  ____XXX_,
  X__X____,
  X____X_X,
  X___X__X,
  ___XXXX_,
  _XX_XXX_,
  _XXXXX__,
  XXX___XX,
  ___X_X__,
  XX___XX_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00EA[ 15] = { /* code 00EA */
  X__X__X_,
  _XXX_X_X,
  X_XX__XX,
  XXX_X_XX,
  XXX_X___,
  XX__X_XX,
  X___XX_X,
  _XX___X_,
  _XX__XXX,
  XXX_X_XX,
  XX___X_X,
  _XXXXXXX,
  X__XX_XX,
  XX_X_XXX,
  __XXX___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00EB[ 15] = { /* code 00EB */
  _X__X__X,
  X______X,
  ___X_X__,
  ___XXX__,
  X_XX___X,
  ______X_,
  _XX__XX_,
  XXXX__X_,
  XX_X_X_X,
  __X_X___,
  _____XXX,
  XXXXXXXX,
  X_X__XXX,
  X_X_X_X_,
  _X_X_XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00EC[ 15] = { /* code 00EC */
  ___X_XXX,
  XXXX_X__,
  XXXX___X,
  ___X__XX,
  __X_X_X_,
  XX_XXX_X,
  X_XX___X,
  __X____X,
  XXXX___X,
  X_X__X__,
  X___XXX_,
  _XX____X,
  _X__XXXX,
  X_XXX_X_,
  _X__XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00ED[ 15] = { /* code 00ED */
  _XXX__XX,
  X_X_X_XX,
  X___X___,
  _X_____X,
  _X_XX___,
  ___XX_XX,
  X_____XX,
  __X_X_XX,
  _XX__X_X,
  X___XXX_,
  ____X_XX,
  __X___XX,
  X_XXXXXX,
  _XX__X_X,
  _X_X____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00EE[ 15] = { /* code 00EE */
  ___X_XXX,
  X_XXXXX_,
  X__X____,
  _XXX_X_X,
  X_X__X_X,
  XX_X_XX_,
  _X__XXX_,
  X____XXX,
  X__X___X,
  __XX_XX_,
  ____XX_X,
  XXX_X_XX,
  X__X__XX,
  _XXXX__X,
  X_XX____};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00EF[ 15] = { /* code 00EF */
  _X_X_XXX,
  _X_XX__X,
  XX____XX,
  __X_X___,
  X_XXX__X,
  _XXXX_XX,
  __XXXXXX,
  _XX__XXX,
  X__XXXXX,
  ____X_XX,
  __XXXXX_,
  XXXX_XXX,
  _____X_X,
  X___XXX_,
  X_X_XX__};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F0[ 15] = { /* code 00F0 */
  X____X_X,
  X_XXX__X,
  _X_____X,
  ____X_X_,
  ___X__X_,
  _____X_X,
  __XX_XXX,
  X_XXX__X,
  _X_XX__X,
  X_XX__XX,
  X_XXX_X_,
  _XXXXX_X,
  _XXX_X_X,
  _X_X_X_X,
  __XXX___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F1[ 15] = { /* code 00F1 */
  XX__XXXX,
  __XX____,
  X__X_X__,
  X__X_XX_,
  __X_XXX_,
  __X__XX_,
  _X__X__X,
  __X_XX_X,
  XX_XX_X_,
  XXX_____,
  X__XXX_X,
  _XXX__X_,
  XXXX___X,
  ____X_XX,
  XX__X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F2[ 15] = { /* code 00F2 */
  _XXX_XXX,
  __XX_X__,
  ___XXXX_,
  _XXXXX__,
  X____XXX,
  X_X_XXX_,
  ___X___X,
  X_XX_X__,
  _XX____X,
  XXXXXX__,
  __XX_X__,
  X_XXX__X,
  X_XX__XX,
  _XX__XX_,
  ____X__X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F3[ 15] = { /* code 00F3 */
  ___XX_X_,
  ___X_X__,
  ___X_XX_,
  _X_XX_X_,
  __X_X__X,
  _XX_____,
  X__XX___,
  X_X__X_X,
  _XX_X_X_,
  XXX_XX_X,
  X__XXX__,
  X__XXX_X,
  X_X___XX,
  XXXXX_X_,
  XX_XX_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F4[ 15] = { /* code 00F4 */
  _XXX_XXX,
  X__X_X__,
  _X_XX_XX,
  X___XXX_,
  _XXX_XX_,
  XX_X_XXX,
  _X_XXX__,
  XX_XXXX_,
  X__X_X__,
  XX_X_X__,
  X______X,
  XX__X___,
  __X___X_,
  X_X__XXX,
  XX____XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F5[ 15] = { /* code 00F5 */
  __X_X___,
  XXXX_X__,
  X__X_X__,
  XXX____X,
  X___XX__,
  XX____XX,
  XX__X___,
  X_XX__XX,
  X___X___,
  __X__X__,
  XX_XX_X_,
  X_XXX_X_,
  X_XX_X_X,
  X___X_XX,
  XXXX__XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F6[ 15] = { /* code 00F6 */
  XX_XX_XX,
  X_____X_,
  ____XXXX,
  X__XX_XX,
  XXXXX___,
  X__X___X,
  XXX_____,
  ___X__X_,
  XXX_X_X_,
  _X_X__XX,
  ___X_XXX,
  _XX__X_X,
  XX_XX_XX,
  __X_X_XX,
  _X__X_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F7[ 15] = { /* code 00F7 */
  X__X_XXX,
  XXX_X_X_,
  XXXXX__X,
  X___XX__,
  XX__X__X,
  XXX_X___,
  X_XXXX__,
  __X____X,
  _____X_X,
  __X_XXXX,
  _XX_XX__,
  __X___XX,
  __X_X_XX,
  ____X___,
  XX_X__X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F8[ 15] = { /* code 00F8 */
  XXX_X_X_,
  XXX_XX_X,
  XXXX____,
  X____X_X,
  XXXX__XX,
  _X_X_XXX,
  X_X__X_X,
  _______X,
  ____X_XX,
  XXXX_XXX,
  __XXXXXX,
  X_X__XXX,
  ___X_X__,
  _X_XXXXX,
  XX__XX_X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00F9[ 15] = { /* code 00F9 */
  _XX__XX_,
  XX_XXX__,
  X___XX_X,
  XX___XX_,
  XXXX__X_,
  XXXX__X_,
  _____XXX,
  _X___XXX,
  __X__XX_,
  X_XXX__X,
  XXX__XX_,
  XXXXX__X,
  XX_XX___,
  X_X_____,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00FA[ 15] = { /* code 00FA */
  _X_XXXX_,
  ___X_XXX,
  XXXX_XX_,
  XX_XXXXX,
  X___X___,
  _X_XXXX_,
  X___XXXX,
  _XX_X___,
  ____XX__,
  X_XXX_XX,
  X__X__XX,
  ____XXX_,
  XXX____X,
  ___X__XX,
  X__XX_XX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00FB[ 15] = { /* code 00FB */
  X_XXXXX_,
  ____XX_X,
  ________,
  X_XXX___,
  X_XXX_XX,
  XX___XXX,
  X__XXX_X,
  ____XXX_,
  ____X___,
  XXX_XXX_,
  X_XXXX_X,
  _X_XXXX_,
  __X_X_XX,
  ___XXXX_,
  __XX___X};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00FC[ 15] = { /* code 00FC */
  __X___XX,
  X_XXXXX_,
  X__XXXX_,
  _XXXX_XX,
  X__X___X,
  XX____XX,
  X___X__X,
  ___X_X_X,
  XXXXX_X_,
  X_X__XX_,
  __X___XX,
  _XX___XX,
  _XXX___X,
  XX__X__X,
  __X__XXX};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00FD[ 15] = { /* code 00FD */
  X_XX__XX,
  ___XX___,
  X___XXX_,
  _XXXX_XX,
  XXX__X_X,
  X_X__XXX,
  XXX___XX,
  XXX_XX__,
  X____XX_,
  _XXXXXX_,
  XX_X_XX_,
  X__X__XX,
  X______X,
  XX___XX_,
  XX__X_X_};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00FE[ 15] = { /* code 00FE */
  XX______,
  _____X_X,
  __X__X_X,
  XX__XX__,
  XX___X__,
  __XXXX__,
  ____XX__,
  XXXX___X,
  X_X____X,
  ___XX_XX,
  ______X_,
  XXX_XX_X,
  X___XXX_,
  _X_X____,
  XXX_X___};

GUI_CONST_STORAGE unsigned char acFontProFontWindows15_00FF[ 15] = { /* code 00FF */
  __X_____,
  X__X____,
  XX__XXXX,
  ___XX_X_,
  __XXXXXX,
  X_X_X__X,
  X_X___X_,
  XX____X_,
  XXX__X_X,
  ___X_X__,
  _X__XX__,
  ______X_,
  X__XXX__,
  ___XX___,
  ___X__XX};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontProFontWindows15_CharInfo[192] = {
   {   7,   7,  1, acFontProFontWindows15_0020 } /* code 0020 */
  ,{   7,   7,  1, acFontProFontWindows15_0021 } /* code 0021 */
  ,{   7,   7,  1, acFontProFontWindows15_0022 } /* code 0022 */
  ,{   7,   7,  1, acFontProFontWindows15_0023 } /* code 0023 */
  ,{   7,   7,  1, acFontProFontWindows15_0024 } /* code 0024 */
  ,{   7,   7,  1, acFontProFontWindows15_0025 } /* code 0025 */
  ,{   7,   7,  1, acFontProFontWindows15_0026 } /* code 0026 */
  ,{   7,   7,  1, acFontProFontWindows15_0027 } /* code 0027 */
  ,{   7,   7,  1, acFontProFontWindows15_0028 } /* code 0028 */
  ,{   7,   7,  1, acFontProFontWindows15_0029 } /* code 0029 */
  ,{   7,   7,  1, acFontProFontWindows15_002A } /* code 002A */
  ,{   7,   7,  1, acFontProFontWindows15_002B } /* code 002B */
  ,{   7,   7,  1, acFontProFontWindows15_002C } /* code 002C */
  ,{   7,   7,  1, acFontProFontWindows15_002D } /* code 002D */
  ,{   7,   7,  1, acFontProFontWindows15_002E } /* code 002E */
  ,{   7,   7,  1, acFontProFontWindows15_002F } /* code 002F */
  ,{   7,   7,  1, acFontProFontWindows15_0030 } /* code 0030 */
  ,{   7,   7,  1, acFontProFontWindows15_0031 } /* code 0031 */
  ,{   7,   7,  1, acFontProFontWindows15_0032 } /* code 0032 */
  ,{   7,   7,  1, acFontProFontWindows15_0033 } /* code 0033 */
  ,{   7,   7,  1, acFontProFontWindows15_0034 } /* code 0034 */
  ,{   7,   7,  1, acFontProFontWindows15_0035 } /* code 0035 */
  ,{   7,   7,  1, acFontProFontWindows15_0036 } /* code 0036 */
  ,{   7,   7,  1, acFontProFontWindows15_0037 } /* code 0037 */
  ,{   7,   7,  1, acFontProFontWindows15_0038 } /* code 0038 */
  ,{   7,   7,  1, acFontProFontWindows15_0039 } /* code 0039 */
  ,{   7,   7,  1, acFontProFontWindows15_003A } /* code 003A */
  ,{   7,   7,  1, acFontProFontWindows15_003B } /* code 003B */
  ,{   7,   7,  1, acFontProFontWindows15_003C } /* code 003C */
  ,{   7,   7,  1, acFontProFontWindows15_003D } /* code 003D */
  ,{   7,   7,  1, acFontProFontWindows15_003E } /* code 003E */
  ,{   7,   7,  1, acFontProFontWindows15_003F } /* code 003F */
  ,{   7,   7,  1, acFontProFontWindows15_0040 } /* code 0040 */
  ,{   7,   7,  1, acFontProFontWindows15_0041 } /* code 0041 */
  ,{   7,   7,  1, acFontProFontWindows15_0042 } /* code 0042 */
  ,{   7,   7,  1, acFontProFontWindows15_0043 } /* code 0043 */
  ,{   7,   7,  1, acFontProFontWindows15_0044 } /* code 0044 */
  ,{   7,   7,  1, acFontProFontWindows15_0045 } /* code 0045 */
  ,{   7,   7,  1, acFontProFontWindows15_0046 } /* code 0046 */
  ,{   7,   7,  1, acFontProFontWindows15_0047 } /* code 0047 */
  ,{   7,   7,  1, acFontProFontWindows15_0048 } /* code 0048 */
  ,{   7,   7,  1, acFontProFontWindows15_0049 } /* code 0049 */
  ,{   7,   7,  1, acFontProFontWindows15_004A } /* code 004A */
  ,{   7,   7,  1, acFontProFontWindows15_004B } /* code 004B */
  ,{   7,   7,  1, acFontProFontWindows15_004C } /* code 004C */
  ,{   7,   7,  1, acFontProFontWindows15_004D } /* code 004D */
  ,{   7,   7,  1, acFontProFontWindows15_004E } /* code 004E */
  ,{   7,   7,  1, acFontProFontWindows15_004F } /* code 004F */
  ,{   7,   7,  1, acFontProFontWindows15_0050 } /* code 0050 */
  ,{   7,   7,  1, acFontProFontWindows15_0051 } /* code 0051 */
  ,{   7,   7,  1, acFontProFontWindows15_0052 } /* code 0052 */
  ,{   7,   7,  1, acFontProFontWindows15_0053 } /* code 0053 */
  ,{   7,   7,  1, acFontProFontWindows15_0054 } /* code 0054 */
  ,{   7,   7,  1, acFontProFontWindows15_0055 } /* code 0055 */
  ,{   7,   7,  1, acFontProFontWindows15_0056 } /* code 0056 */
  ,{   7,   7,  1, acFontProFontWindows15_0057 } /* code 0057 */
  ,{   7,   7,  1, acFontProFontWindows15_0058 } /* code 0058 */
  ,{   7,   7,  1, acFontProFontWindows15_0059 } /* code 0059 */
  ,{   7,   7,  1, acFontProFontWindows15_005A } /* code 005A */
  ,{   7,   7,  1, acFontProFontWindows15_005B } /* code 005B */
  ,{   7,   7,  1, acFontProFontWindows15_005C } /* code 005C */
  ,{   7,   7,  1, acFontProFontWindows15_005D } /* code 005D */
  ,{   7,   7,  1, acFontProFontWindows15_005E } /* code 005E */
  ,{   7,   7,  1, acFontProFontWindows15_005F } /* code 005F */
  ,{   7,   7,  1, acFontProFontWindows15_0060 } /* code 0060 */
  ,{   7,   7,  1, acFontProFontWindows15_0061 } /* code 0061 */
  ,{   7,   7,  1, acFontProFontWindows15_0062 } /* code 0062 */
  ,{   7,   7,  1, acFontProFontWindows15_0063 } /* code 0063 */
  ,{   7,   7,  1, acFontProFontWindows15_0064 } /* code 0064 */
  ,{   7,   7,  1, acFontProFontWindows15_0065 } /* code 0065 */
  ,{   7,   7,  1, acFontProFontWindows15_0066 } /* code 0066 */
  ,{   7,   7,  1, acFontProFontWindows15_0067 } /* code 0067 */
  ,{   7,   7,  1, acFontProFontWindows15_0068 } /* code 0068 */
  ,{   7,   7,  1, acFontProFontWindows15_0069 } /* code 0069 */
  ,{   7,   7,  1, acFontProFontWindows15_006A } /* code 006A */
  ,{   7,   7,  1, acFontProFontWindows15_006B } /* code 006B */
  ,{   7,   7,  1, acFontProFontWindows15_006C } /* code 006C */
  ,{   7,   7,  1, acFontProFontWindows15_006D } /* code 006D */
  ,{   7,   7,  1, acFontProFontWindows15_006E } /* code 006E */
  ,{   7,   7,  1, acFontProFontWindows15_006F } /* code 006F */
  ,{   7,   7,  1, acFontProFontWindows15_0070 } /* code 0070 */
  ,{   7,   7,  1, acFontProFontWindows15_0071 } /* code 0071 */
  ,{   7,   7,  1, acFontProFontWindows15_0072 } /* code 0072 */
  ,{   7,   7,  1, acFontProFontWindows15_0073 } /* code 0073 */
  ,{   7,   7,  1, acFontProFontWindows15_0074 } /* code 0074 */
  ,{   7,   7,  1, acFontProFontWindows15_0075 } /* code 0075 */
  ,{   7,   7,  1, acFontProFontWindows15_0076 } /* code 0076 */
  ,{   7,   7,  1, acFontProFontWindows15_0077 } /* code 0077 */
  ,{   7,   7,  1, acFontProFontWindows15_0078 } /* code 0078 */
  ,{   7,   7,  1, acFontProFontWindows15_0079 } /* code 0079 */
  ,{   7,   7,  1, acFontProFontWindows15_007A } /* code 007A */
  ,{   7,   7,  1, acFontProFontWindows15_007B } /* code 007B */
  ,{   7,   7,  1, acFontProFontWindows15_007C } /* code 007C */
  ,{   7,   7,  1, acFontProFontWindows15_007D } /* code 007D */
  ,{   7,   7,  1, acFontProFontWindows15_007E } /* code 007E */
  ,{   7,   7,  1, acFontProFontWindows15_007F } /* code 007F */
  ,{   7,   7,  1, acFontProFontWindows15_00A0 } /* code 00A0 */
  ,{   7,   7,  1, acFontProFontWindows15_00A1 } /* code 00A1 */
  ,{   7,   7,  1, acFontProFontWindows15_00A2 } /* code 00A2 */
  ,{   7,   7,  1, acFontProFontWindows15_00A3 } /* code 00A3 */
  ,{   7,   7,  1, acFontProFontWindows15_00A4 } /* code 00A4 */
  ,{   7,   7,  1, acFontProFontWindows15_00A5 } /* code 00A5 */
  ,{   7,   7,  1, acFontProFontWindows15_00A6 } /* code 00A6 */
  ,{   7,   7,  1, acFontProFontWindows15_00A7 } /* code 00A7 */
  ,{   7,   7,  1, acFontProFontWindows15_00A8 } /* code 00A8 */
  ,{   7,   7,  1, acFontProFontWindows15_00A9 } /* code 00A9 */
  ,{   7,   7,  1, acFontProFontWindows15_00AA } /* code 00AA */
  ,{   7,   7,  1, acFontProFontWindows15_00AB } /* code 00AB */
  ,{   7,   7,  1, acFontProFontWindows15_00AC } /* code 00AC */
  ,{   7,   7,  1, acFontProFontWindows15_00AD } /* code 00AD */
  ,{   7,   7,  1, acFontProFontWindows15_00AE } /* code 00AE */
  ,{   7,   7,  1, acFontProFontWindows15_00AF } /* code 00AF */
  ,{   7,   7,  1, acFontProFontWindows15_00B0 } /* code 00B0 */
  ,{   7,   7,  1, acFontProFontWindows15_00B1 } /* code 00B1 */
  ,{   7,   7,  1, acFontProFontWindows15_00B2 } /* code 00B2 */
  ,{   7,   7,  1, acFontProFontWindows15_00B3 } /* code 00B3 */
  ,{   7,   7,  1, acFontProFontWindows15_00B4 } /* code 00B4 */
  ,{   7,   7,  1, acFontProFontWindows15_00B5 } /* code 00B5 */
  ,{   7,   7,  1, acFontProFontWindows15_00B6 } /* code 00B6 */
  ,{   7,   7,  1, acFontProFontWindows15_00B7 } /* code 00B7 */
  ,{   7,   7,  1, acFontProFontWindows15_00B8 } /* code 00B8 */
  ,{   7,   7,  1, acFontProFontWindows15_00B9 } /* code 00B9 */
  ,{   7,   7,  1, acFontProFontWindows15_00BA } /* code 00BA */
  ,{   7,   7,  1, acFontProFontWindows15_00BB } /* code 00BB */
  ,{   7,   7,  1, acFontProFontWindows15_00BC } /* code 00BC */
  ,{   7,   7,  1, acFontProFontWindows15_00BD } /* code 00BD */
  ,{   7,   7,  1, acFontProFontWindows15_00BE } /* code 00BE */
  ,{   7,   7,  1, acFontProFontWindows15_00BF } /* code 00BF */
  ,{   7,   7,  1, acFontProFontWindows15_00C0 } /* code 00C0 */
  ,{   7,   7,  1, acFontProFontWindows15_00C1 } /* code 00C1 */
  ,{   7,   7,  1, acFontProFontWindows15_00C2 } /* code 00C2 */
  ,{   7,   7,  1, acFontProFontWindows15_00C3 } /* code 00C3 */
  ,{   7,   7,  1, acFontProFontWindows15_00C4 } /* code 00C4 */
  ,{   7,   7,  1, acFontProFontWindows15_00C5 } /* code 00C5 */
  ,{   7,   7,  1, acFontProFontWindows15_00C6 } /* code 00C6 */
  ,{   7,   7,  1, acFontProFontWindows15_00C7 } /* code 00C7 */
  ,{   7,   7,  1, acFontProFontWindows15_00C8 } /* code 00C8 */
  ,{   7,   7,  1, acFontProFontWindows15_00C9 } /* code 00C9 */
  ,{   7,   7,  1, acFontProFontWindows15_00CA } /* code 00CA */
  ,{   7,   7,  1, acFontProFontWindows15_00CB } /* code 00CB */
  ,{   7,   7,  1, acFontProFontWindows15_00CC } /* code 00CC */
  ,{   7,   7,  1, acFontProFontWindows15_00CD } /* code 00CD */
  ,{   7,   7,  1, acFontProFontWindows15_00CE } /* code 00CE */
  ,{   7,   7,  1, acFontProFontWindows15_00CF } /* code 00CF */
  ,{   7,   7,  1, acFontProFontWindows15_00D0 } /* code 00D0 */
  ,{   7,   7,  1, acFontProFontWindows15_00D1 } /* code 00D1 */
  ,{   7,   7,  1, acFontProFontWindows15_00D2 } /* code 00D2 */
  ,{   7,   7,  1, acFontProFontWindows15_00D3 } /* code 00D3 */
  ,{   7,   7,  1, acFontProFontWindows15_00D4 } /* code 00D4 */
  ,{   7,   7,  1, acFontProFontWindows15_00D5 } /* code 00D5 */
  ,{   7,   7,  1, acFontProFontWindows15_00D6 } /* code 00D6 */
  ,{   7,   7,  1, acFontProFontWindows15_00D7 } /* code 00D7 */
  ,{   7,   7,  1, acFontProFontWindows15_00D8 } /* code 00D8 */
  ,{   7,   7,  1, acFontProFontWindows15_00D9 } /* code 00D9 */
  ,{   7,   7,  1, acFontProFontWindows15_00DA } /* code 00DA */
  ,{   7,   7,  1, acFontProFontWindows15_00DB } /* code 00DB */
  ,{   7,   7,  1, acFontProFontWindows15_00DC } /* code 00DC */
  ,{   7,   7,  1, acFontProFontWindows15_00DD } /* code 00DD */
  ,{   7,   7,  1, acFontProFontWindows15_00DE } /* code 00DE */
  ,{   7,   7,  1, acFontProFontWindows15_00DF } /* code 00DF */
  ,{   7,   7,  1, acFontProFontWindows15_00E0 } /* code 00E0 */
  ,{   7,   7,  1, acFontProFontWindows15_00E1 } /* code 00E1 */
  ,{   7,   7,  1, acFontProFontWindows15_00E2 } /* code 00E2 */
  ,{   7,   7,  1, acFontProFontWindows15_00E3 } /* code 00E3 */
  ,{   7,   7,  1, acFontProFontWindows15_00E4 } /* code 00E4 */
  ,{   7,   7,  1, acFontProFontWindows15_00E5 } /* code 00E5 */
  ,{   7,   7,  1, acFontProFontWindows15_00E6 } /* code 00E6 */
  ,{   7,   7,  1, acFontProFontWindows15_00E7 } /* code 00E7 */
  ,{   7,   7,  1, acFontProFontWindows15_00E8 } /* code 00E8 */
  ,{   7,   7,  1, acFontProFontWindows15_00E9 } /* code 00E9 */
  ,{   7,   7,  1, acFontProFontWindows15_00EA } /* code 00EA */
  ,{   7,   7,  1, acFontProFontWindows15_00EB } /* code 00EB */
  ,{   7,   7,  1, acFontProFontWindows15_00EC } /* code 00EC */
  ,{   7,   7,  1, acFontProFontWindows15_00ED } /* code 00ED */
  ,{   7,   7,  1, acFontProFontWindows15_00EE } /* code 00EE */
  ,{   7,   7,  1, acFontProFontWindows15_00EF } /* code 00EF */
  ,{   7,   7,  1, acFontProFontWindows15_00F0 } /* code 00F0 */
  ,{   7,   7,  1, acFontProFontWindows15_00F1 } /* code 00F1 */
  ,{   7,   7,  1, acFontProFontWindows15_00F2 } /* code 00F2 */
  ,{   7,   7,  1, acFontProFontWindows15_00F3 } /* code 00F3 */
  ,{   7,   7,  1, acFontProFontWindows15_00F4 } /* code 00F4 */
  ,{   7,   7,  1, acFontProFontWindows15_00F5 } /* code 00F5 */
  ,{   7,   7,  1, acFontProFontWindows15_00F6 } /* code 00F6 */
  ,{   7,   7,  1, acFontProFontWindows15_00F7 } /* code 00F7 */
  ,{   7,   7,  1, acFontProFontWindows15_00F8 } /* code 00F8 */
  ,{   7,   7,  1, acFontProFontWindows15_00F9 } /* code 00F9 */
  ,{   7,   7,  1, acFontProFontWindows15_00FA } /* code 00FA */
  ,{   7,   7,  1, acFontProFontWindows15_00FB } /* code 00FB */
  ,{   7,   7,  1, acFontProFontWindows15_00FC } /* code 00FC */
  ,{   7,   7,  1, acFontProFontWindows15_00FD } /* code 00FD */
  ,{   7,   7,  1, acFontProFontWindows15_00FE } /* code 00FE */
  ,{   7,   7,  1, acFontProFontWindows15_00FF } /* code 00FF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontProFontWindows15_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontProFontWindows15_CharInfo[ 96] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontProFontWindows15_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontProFontWindows15_CharInfo[  0] /* address of first character */
  ,&GUI_FontProFontWindows15_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontProFontWindows15 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,15 /* height of font  */
  ,15 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,&GUI_FontProFontWindows15_Prop1
};

