/*
  C-file generated by µC/GUI-FontConvert Demo  V2.18
  Compiled:    Jul 17 2003 at 08:42:22

  (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com

  Source file: UbuntuMono18.c
  Font:        Ubuntu Mono
  Height:      18
*/

#include "GUI.H"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontUbuntuMono18;

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0020[ 18] = { /* code 0020 */
  X__XXX__,
  X__XX_XX,
  X_XXX__X,
  ____XXX_,
  X_X_____,
  __X____X,
  _X_XX__X,
  _XX____X,
  ___XXX__,
  XXXX_XXX,
  _XX_X_X_,
  _X__X__X,
  _X___X_X,
  _XX_X_X_,
  XXXXXXXX,
  _XXXXXXX,
  __XXXXXX,
  _XX__XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0021[ 18] = { /* code 0021 */
  X__XX_X_,
  X__X_X_X,
  XX_XXXX_,
  _XXXX_XX,
  XXX___XX,
  _XX_XXXX,
  ____XX__,
  __XX___X,
  X_X__X_X,
  _XXX_X__,
  _XX_X___,
  XX_X___X,
  _X___XX_,
  _____XX_,
  X_X_XXX_,
  X____XXX,
  X___X_X_,
  X_X_XX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0022[ 18] = { /* code 0022 */
  XX___XX_,
  _______X,
  XXX___X_,
  ___X____,
  X__X_X_X,
  XXXX_XX_,
  X_XX_XX_,
  _X_X____,
  XXXX_X__,
  X_X_X_XX,
  ___X____,
  XXXX_X_X,
  __X_XX_X,
  X__XX___,
  X___X__X,
  _XXXXXXX,
  X_XX____,
  _X__X_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0023[ 18] = { /* code 0023 */
  _X_XX__X,
  X____XX_,
  X_X__X_X,
  __XX___X,
  _X__X__X,
  ________,
  XXXX____,
  X_XXXXX_,
  _X____XX,
  ___XXX__,
  _XXXX__X,
  _X_XX___,
  XX_XXX_X,
  _X____XX,
  XXX_X___,
  XXXXXXX_,
  ___XX_X_,
  _XXX_XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0024[ 18] = { /* code 0024 */
  _XX_X__X,
  XX_X_XX_,
  _X_XX_X_,
  X_X__X__,
  _XX_XXX_,
  XXXX_XX_,
  ___X____,
  XXXXXXXX,
  _XXX_XXX,
  _X___XXX,
  X_XXX_X_,
  XXXX_X__,
  X__X_XXX,
  XXX__X_X,
  _XX_____,
  XX_X__XX,
  ____X_XX,
  ___X____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0025[ 18] = { /* code 0025 */
  X_XX_X_X,
  ___XXX_X,
  _X__X__X,
  __X_XXXX,
  X___X__X,
  X__X__X_,
  __XXX__X,
  X_X__XXX,
  XX_XXXX_,
  XX_XX___,
  __XXXX__,
  _X_XXX__,
  __X_X__X,
  X_X_X_X_,
  XX__XX__,
  X_XX_XX_,
  X__X__X_,
  X_XX__XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0026[ 18] = { /* code 0026 */
  X_XXXXXX,
  XXXX_X_X,
  XX_X_XXX,
  _XX_XXX_,
  _X_X__X_,
  X__XX___,
  X_XX_X_X,
  X__XX_X_,
  XX_XX_XX,
  XX_X_X_X,
  X__X___X,
  X_X__X__,
  XXXXX_X_,
  __XX____,
  _XXXXX_X,
  _XX_X__X,
  _X_XX_X_,
  _XX_____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0027[ 18] = { /* code 0027 */
  XX_XXXXX,
  ___X__X_,
  __X_XXXX,
  _XXXX__X,
  XXX_XX_X,
  XXXX__X_,
  _X_XX_X_,
  _XX_____,
  X__X_X_X,
  XX_XXX_X,
  _XXX_X_X,
  X_XX_X_X,
  _XX_XXX_,
  XXXX__XX,
  X_XX__X_,
  __X_X___,
  X__XX_XX,
  XX___X__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0028[ 18] = { /* code 0028 */
  X_______,
  _XX__XX_,
  X____XX_,
  __X_X__X,
  __XXXX_X,
  __XXXXXX,
  X_X_X_XX,
  _X_XX__X,
  _X_X_XXX,
  __XX____,
  X__X__XX,
  X_X_X___,
  XX_X__XX,
  X_XX_X_X,
  _X_XX_X_,
  ___XX___,
  _XXXXX__,
  XXX__XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0029[ 18] = { /* code 0029 */
  XXXXX_X_,
  __XX_X_X,
  __XX___X,
  XX____X_,
  XXX_XXX_,
  X_X_X___,
  __XXX_XX,
  X__X_X_X,
  X_X___XX,
  XX__XXXX,
  ____X__X,
  _X__X_XX,
  ___XXX__,
  XX__X_X_,
  XX___XX_,
  XXXXX__X,
  XX___X_X,
  XXX_____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_002A[ 18] = { /* code 002A */
  _X_XXXXX,
  __X_X___,
  ___XX_X_,
  __XXX_X_,
  ____X_XX,
  XX_X____,
  ____XXXX,
  X__XXX__,
  _X__X_X_,
  XXXXXX_X,
  ___X_X__,
  X_______,
  _X_X_XX_,
  ___XX__X,
  XX_XX__X,
  X__XXX_X,
  XX_X_XXX,
  X__XXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_002B[ 18] = { /* code 002B */
  _X_XXXX_,
  _X__X__X,
  X__X__X_,
  X_XX_X_X,
  ______XX,
  X__XX_X_,
  X__XX___,
  XX_X_XXX,
  _X_X____,
  _X____X_,
  XX_X_X_X,
  __X__XX_,
  XXXX__X_,
  _X__XXX_,
  ___X___X,
  X_______,
  XXXX_X__,
  _X__XXXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_002C[ 18] = { /* code 002C */
  X_X_____,
  XXXX___X,
  XXX_XXXX,
  XX__X_XX,
  _XXXX_XX,
  XXX_X_X_,
  XX_X___X,
  ____X_X_,
  X_____X_,
  XX___XXX,
  XX__X_X_,
  _XX__XX_,
  X__X__XX,
  __XXXX__,
  _XXX_X_X,
  __XX_XX_,
  _XX_XXXX,
  X_XX_X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_002D[ 18] = { /* code 002D */
  XX_XXXXX,
  __X_XXX_,
  X_______,
  X__X_XX_,
  _____XXX,
  XX_X____,
  X______X,
  XX_XX___,
  _XX_____,
  X____X_X,
  XXX__X__,
  _XXX_XX_,
  XX__XX_X,
  X_XXX_X_,
  ____XX_X,
  XXXX_X_X,
  __XX__XX,
  XX____XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_002E[ 18] = { /* code 002E */
  XXX____X,
  ______XX,
  XX_XXXXX,
  _X__XX__,
  XX_____X,
  ___XX___,
  X_X__X__,
  XXX_XX_X,
  XXXXXX_X,
  ______XX,
  X____X__,
  _X____XX,
  XX____X_,
  XX_X_X__,
  __XX__XX,
  _XX_XXXX,
  __XXX__X,
  _X__X__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_002F[ 18] = { /* code 002F */
  X_____XX,
  XX_XX_X_,
  X_X___XX,
  _____XXX,
  _XX___XX,
  __XXXXXX,
  X_____X_,
  _X_XXXX_,
  _XXXXXXX,
  XX___X__,
  XXXX_X_X,
  XX_X_XXX,
  XX_XXXXX,
  X_XX_XXX,
  __XX____,
  _X_X_X__,
  ___XXXX_,
  XX___X__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0030[ 18] = { /* code 0030 */
  XX_X_XXX,
  XXX__XXX,
  X_XX_XXX,
  ____X_XX,
  ___XX_XX,
  X_X___XX,
  X_XXXXX_,
  X_XX_XXX,
  _XX_X___,
  XXXX_X__,
  XX__X_XX,
  _X_X__XX,
  X_X_X_X_,
  ____X___,
  XX__X__X,
  _X_X__X_,
  _XXXX__X,
  X__XX___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0031[ 18] = { /* code 0031 */
  _X_X_X__,
  _X_XXX__,
  XXX_XX__,
  XXX_X___,
  _____XX_,
  X_XX___X,
  _X_XX___,
  X_XX_XX_,
  ___X_XXX,
  X_X___X_,
  X___XX_X,
  XX_XXX_X,
  _X_XX___,
  _XXXXXX_,
  X____X_X,
  _XXXX_X_,
  X____X__,
  ________};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0032[ 18] = { /* code 0032 */
  _X_XXX_X,
  _X_XXX_X,
  ______XX,
  XX_X____,
  __XXXX_X,
  XXXX_X__,
  _____XXX,
  _____X__,
  X_XX__XX,
  ___X_XXX,
  _X__XX__,
  XX_XXX__,
  __XXXXX_,
  _XX__X__,
  _X___XXX,
  XX_X__X_,
  __X_X___,
  XX____XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0033[ 18] = { /* code 0033 */
  X_XX_X__,
  _X_X____,
  ___XXX_X,
  X_XX_XX_,
  XXX_X_XX,
  _X_X_XX_,
  X__X_XX_,
  X___X___,
  _X_X_X_X,
  _XXXXX_X,
  X_X__XXX,
  X_X__X__,
  X_____XX,
  XXXXX_X_,
  __XX____,
  _XXXXX_X,
  XXXX___X,
  X_X_X__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0034[ 18] = { /* code 0034 */
  X__X_X__,
  XX_X_X_X,
  XXX_X_XX,
  ___X_X__,
  ____X_X_,
  XXXX__XX,
  ____X_X_,
  XX__XXX_,
  __X_XXX_,
  X_XXX_XX,
  __X_X___,
  __XXX__X,
  _X__XXX_,
  ___X_XXX,
  X___XX_X,
  __X__XXX,
  X_X__XXX,
  X__X_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0035[ 18] = { /* code 0035 */
  __X__XXX,
  _X_XXXXX,
  _____XXX,
  _X____X_,
  X_____XX,
  XXXX_X_X,
  _XXX__X_,
  _X_XX_XX,
  X_XX____,
  _XXX_X_X,
  _____XX_,
  XXX__XXX,
  XX__X___,
  ___XXX__,
  _XX_X___,
  __XX_X_X,
  _XXX__XX,
  _XXX____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0036[ 18] = { /* code 0036 */
  X___X_X_,
  X_X_X_X_,
  XX___XXX,
  _X___XX_,
  _XXXX___,
  _XX__X__,
  __XXX_XX,
  X_X_____,
  _XX_____,
  X_XXXX_X,
  _XXX__X_,
  ___XX_X_,
  ____X_X_,
  X_XX_XXX,
  X___XXXX,
  ____X_XX,
  X___XXXX,
  ___X_XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0037[ 18] = { /* code 0037 */
  XX__XXXX,
  _XXXX_XX,
  __X_X___,
  X____X__,
  X_X__XXX,
  X__X_X_X,
  XXX_X___,
  X_______,
  _XXXX_X_,
  _XX_X_XX,
  XX____XX,
  __XX_X_X,
  X__XXXXX,
  X_X_XX_X,
  _X_X___X,
  _XX_XX_X,
  XX_____X,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0038[ 18] = { /* code 0038 */
  _X_XX_XX,
  X__XX_X_,
  ___XX___,
  _____XX_,
  __X__XXX,
  X___X__X,
  _X____X_,
  XXX_XXXX,
  XXXX__XX,
  X_XX_XXX,
  _XXX__X_,
  __XXXX__,
  X_XX_XX_,
  __XXXXX_,
  _XX_X___,
  _XX____X,
  __X_XXX_,
  X__XX_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0039[ 18] = { /* code 0039 */
  X_X__X__,
  __XXXXX_,
  X_X_XX__,
  __XXX___,
  ___X__XX,
  _____XX_,
  _XX_XXX_,
  ___X_XX_,
  XX_X__XX,
  X__XX__X,
  _X______,
  _XXX_X__,
  ____XX__,
  XX______,
  X___X__X,
  X____X_X,
  ____XXXX,
  XX__XX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_003A[ 18] = { /* code 003A */
  XX__X_XX,
  __X___XX,
  XXX_X__X,
  X_X_X___,
  _X_XXXX_,
  XX_X_XXX,
  __XXXXX_,
  _XX_XX__,
  __X__X_X,
  XXX_X__X,
  __X_X___,
  XXX____X,
  _XXXXX_X,
  _XX__X_X,
  XX_X_XXX,
  _XX__X__,
  XX__X_X_,
  ___XXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_003B[ 18] = { /* code 003B */
  X_X_X__X,
  XX_X_XXX,
  __XX__X_,
  __XX_XX_,
  __X___XX,
  XX__X___,
  XXXXXX_X,
  X_XX__XX,
  _X_XXXX_,
  _X_X__X_,
  XX_XXXXX,
  _X_XX_X_,
  __XXXX__,
  XXX__XXX,
  X_XXXX_X,
  _X_X_X_X,
  X__X___X,
  XX_XX__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_003C[ 18] = { /* code 003C */
  ___X_X__,
  XXXX_XX_,
  XX__XXX_,
  XX______,
  X_XXXX__,
  X_X_____,
  XXX__XXX,
  _XX_X_XX,
  _X_XX__X,
  X_XXX_X_,
  XX__X___,
  XX__X_XX,
  __X____X,
  X_X__X__,
  X_XXXX__,
  X_X_____,
  X__XX_XX,
  __XX_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_003D[ 18] = { /* code 003D */
  XXX_XXXX,
  XX__XX__,
  _XX__X__,
  XXX_X_XX,
  _X_XX___,
  XXXXX___,
  XX_XXXX_,
  X_X__X__,
  __XXXXXX,
  ___XXX__,
  XX_XXXXX,
  XXXXXX__,
  ______X_,
  __X__X__,
  X_X_X__X,
  XXXX_XX_,
  ______X_,
  X__X_X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_003E[ 18] = { /* code 003E */
  X____X_X,
  _XXX_XX_,
  XXX___XX,
  XXX__X_X,
  X___X_XX,
  _XX__X__,
  _XX_X_XX,
  ____X___,
  _XX__XXX,
  _X______,
  _X___X_X,
  XX_X_X_X,
  _XXX_XX_,
  _X_X_XXX,
  ___X__XX,
  X_XXX_XX,
  _XXX_XX_,
  XX__XXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_003F[ 18] = { /* code 003F */
  X__X_X_X,
  XXXX____,
  X_______,
  _XXXX_XX,
  ____X___,
  X__XX_X_,
  ___X___X,
  XXX_XXX_,
  X_XXX_X_,
  _X_X__XX,
  ____XX__,
  XX_X_XX_,
  XXX_X_X_,
  X_X____X,
  ___X_X_X,
  _XXXX_XX,
  __X__X__,
  XXXXXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0040[ 18] = { /* code 0040 */
  XX_XX___,
  XX_XX_XX,
  _XXXX___,
  X_X___X_,
  ______XX,
  _X_XX_X_,
  _XXXXXXX,
  __XXX___,
  XX___X__,
  _XXX_XXX,
  XX_XX_XX,
  X_X___XX,
  XX__XXXX,
  ___X_X_X,
  XX_X__XX,
  _XXXX_XX,
  X_X___X_,
  XXX_____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0041[ 18] = { /* code 0041 */
  _X_XX_XX,
  _XXX___X,
  _XXX_X__,
  ________,
  XX__X__X,
  __XX_XX_,
  XXXX_X__,
  X_XXXX_X,
  _XXX_XX_,
  XXXX____,
  XX__XXX_,
  X_X_X_X_,
  _XX_X___,
  _XXXXXXX,
  XX_XXXX_,
  ________,
  _X_XXXXX,
  _X_XXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0042[ 18] = { /* code 0042 */
  XXX_XX_X,
  XXXXXXXX,
  XX__XXX_,
  _X__XXXX,
  _XX_X__X,
  _XXX_XXX,
  _XXX_XXX,
  _X_X_XX_,
  _X_X_XX_,
  _X_X____,
  _X_XXXX_,
  XXX_XX_X,
  _XXX___X,
  ___XXX_X,
  _XXXX___,
  XXXXX___,
  ___X__X_,
  X_XX____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0043[ 18] = { /* code 0043 */
  _XXX_X_X,
  _X___X_X,
  _XXXX_XX,
  __XXXX_X,
  X__XX_X_,
  XXXXXX__,
  _XXXXXXX,
  XX___X_X,
  XXXXXXXX,
  XXXX_X_X,
  X___XX__,
  XX_XXX__,
  _X__XX__,
  XX_X_X_X,
  X__XX_XX,
  XX___X_X,
  X_XX_X__,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0044[ 18] = { /* code 0044 */
  __XX_X__,
  _X_X_XX_,
  X___X_XX,
  _X_X__X_,
  _X___X_X,
  X___X_XX,
  ___XX___,
  XXX__X_X,
  __X__X_X,
  XX____XX,
  _XX__XXX,
  X____XX_,
  XX_XXX__,
  X__XXXX_,
  _X__XXX_,
  X_XXX___,
  ___X__X_,
  ___XXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0045[ 18] = { /* code 0045 */
  _X_X__X_,
  X___X_XX,
  _XXX__X_,
  XX_X_X__,
  X_XX__XX,
  XXXXXX_X,
  X_XX___X,
  __X___XX,
  __XXXXXX,
  X_XXXXX_,
  XX_XXX__,
  __X___XX,
  _____X_X,
  _X__X__X,
  X__XXX_X,
  __XX_XX_,
  _X____XX,
  __X__XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0046[ 18] = { /* code 0046 */
  XX__XX__,
  X___XXX_,
  XX_XX__X,
  _XX_XXXX,
  __X__XXX,
  ___XXX__,
  _XX__X__,
  _____X_X,
  X_XXX___,
  __X_XXXX,
  X_XXXXXX,
  XX__XX_X,
  X_X_XXX_,
  __XXXX__,
  X_X_XXX_,
  ___XX_XX,
  XXX_X_XX,
  ___XX_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0047[ 18] = { /* code 0047 */
  X_XX___X,
  _XX___XX,
  _XXX__XX,
  XXXXXX__,
  __XXX___,
  __XXXX__,
  XXXX____,
  ___XX_XX,
  X_X_X_XX,
  X_X__X__,
  _XXX__XX,
  __XX__X_,
  X_X_XXX_,
  __XXXXXX,
  _XXX_X_X,
  _X_XXXX_,
  XX_X_XXX,
  XXX_XX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0048[ 18] = { /* code 0048 */
  _XXX___X,
  X_X___XX,
  _X_X_XXX,
  XXX_XXXX,
  X__XXXX_,
  _X_____X,
  X__X_X_X,
  X_X_X_X_,
  ______XX,
  __XXXX__,
  _XX___X_,
  _XX_XXX_,
  _XXXX__X,
  _X__X_XX,
  _XXX_X__,
  XX____XX,
  __X____X,
  _XX___X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0049[ 18] = { /* code 0049 */
  ____X_XX,
  X_____XX,
  ___X_XX_,
  X_XX_X_X,
  XX_X__X_,
  XX_X___X,
  XX__X_X_,
  ___X___X,
  _XXX__X_,
  _XX_X_XX,
  XXX__X_X,
  __XX___X,
  ______X_,
  XXX__X_X,
  _X____X_,
  _XXXXX_X,
  _X______,
  _X___X__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_004A[ 18] = { /* code 004A */
  XX_X___X,
  XX_X__XX,
  _XX__X__,
  _X_XXXX_,
  XXX_X_X_,
  _X_XXX__,
  X_____X_,
  __X___X_,
  _X______,
  X____XX_,
  __XXX_X_,
  XX__X__X,
  __X__XXX,
  X__XXX_X,
  ___XX___,
  _X__X___,
  _X_X____,
  _XX__X__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_004B[ 18] = { /* code 004B */
  _XX_____,
  X_X___XX,
  __X__XXX,
  __XX___X,
  X__X__X_,
  XX__XX__,
  X_XXXXX_,
  __X_____,
  _X__XX__,
  _XXXX_XX,
  X___XXX_,
  X_X___X_,
  __X___X_,
  X__XX_X_,
  __X__XXX,
  XXXXXXXX,
  _X_XXXX_,
  __X__XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_004C[ 18] = { /* code 004C */
  _XXX_X__,
  _XXXXX__,
  _X_XXXX_,
  __XX_XX_,
  XX_XX__X,
  X__X_X_X,
  X_XXXXXX,
  _X____XX,
  _XXX_XX_,
  _X____X_,
  __XX_XX_,
  XXX___X_,
  __XXXXX_,
  _X__XXX_,
  ___XX__X,
  _X_X_XX_,
  __X___XX,
  __XX___X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_004D[ 18] = { /* code 004D */
  ____XXX_,
  X__XXX__,
  ____XXXX,
  XXXXXXXX,
  XXX_X___,
  XXXX___X,
  XX_XXX__,
  _X_XXX_X,
  __XX___X,
  __XXX__X,
  _X__X_XX,
  ____XX_X,
  XXX___XX,
  _X_X____,
  ___X_X_X,
  _XXXXX_X,
  XXXX__X_,
  _X___XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_004E[ 18] = { /* code 004E */
  _X__X_X_,
  _XXXX___,
  XXXX___X,
  XX_XXXX_,
  _X______,
  X__XXX__,
  __X__X_X,
  ___X_X_X,
  XX_XX_XX,
  XXX_X___,
  X_X_X_X_,
  __XXX_XX,
  X__XX___,
  XX_X___X,
  XXX___X_,
  X_X____X,
  X__X__X_,
  X_XXX_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_004F[ 18] = { /* code 004F */
  X_X_XXXX,
  X_XX___X,
  XX_XXXXX,
  X_____XX,
  X____XX_,
  _XXX___X,
  __X_XX_X,
  X_X_____,
  ___X___X,
  X__X_X_X,
  X_X_X___,
  _X_XXX_X,
  ____X_X_,
  _X_X__XX,
  _XXX__XX,
  __X_X_XX,
  __X__X__,
  XX_XXX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0050[ 18] = { /* code 0050 */
  X_____X_,
  __X___XX,
  __X__XX_,
  ___XXX_X,
  X__X___X,
  XX_X____,
  X__X__X_,
  _XX_XX__,
  _XXX_X_X,
  XXXX____,
  __X_X_X_,
  XXXX_X_X,
  X___X_XX,
  _XX___X_,
  XXX__XXX,
  __XXX_XX,
  X_X_X__X,
  X__XXX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0051[ 18] = { /* code 0051 */
  X____X_X,
  XX_XXXX_,
  XXX_XXXX,
  X__X__X_,
  __X_X___,
  XXX_X___,
  _____X_X,
  __XXXXXX,
  XX___XX_,
  X_XX_X__,
  XXX_X_XX,
  __X__XXX,
  __X__XX_,
  _X_X_XX_,
  XX_XX__X,
  _XXXXX__,
  _X_X___X,
  XXXX_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0052[ 18] = { /* code 0052 */
  XXX__XXX,
  __XX_XX_,
  _XX_X__X,
  X__XX__X,
  XX__XX_X,
  XXXX____,
  XX_X_XX_,
  XXXX___X,
  __XXX__X,
  _XX__X_X,
  _XX_____,
  X____XXX,
  X_XXX_XX,
  _XX___XX,
  X_XX_XX_,
  __X__X_X,
  X_______,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0053[ 18] = { /* code 0053 */
  X__XX___,
  X__XXXXX,
  XXX_XXXX,
  __XXXXX_,
  __X_X_X_,
  X_X_XX__,
  __X_X_X_,
  XXXX_XX_,
  XXX_X__X,
  XX_XXXX_,
  XX_XXX_X,
  X_X____X,
  _X____X_,
  _XXXXX__,
  ______XX,
  ____XXX_,
  _X_XXX_X,
  XXX_X___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0054[ 18] = { /* code 0054 */
  __X_____,
  XX_X____,
  ___XX_X_,
  X_______,
  X_XX____,
  X__XXX__,
  __X__X__,
  X___XX_X,
  _XXXXXX_,
  X_XX_XXX,
  X_X_X__X,
  X_X__XXX,
  XXX__X__,
  _XX_XX__,
  XXX___XX,
  _XX_XXX_,
  _XXX__X_,
  ___XXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0055[ 18] = { /* code 0055 */
  XXXX__X_,
  XX_XX__X,
  X_XX___X,
  X_XXX__X,
  X_X_XX_X,
  XX__XX__,
  X_X_XXXX,
  _X_X_XXX,
  _XX____X,
  X___X_XX,
  _XX_XX_X,
  X___X__X,
  XXXX_XX_,
  X____XXX,
  __X_XX_X,
  X_XX___X,
  XXXX____,
  ___XXX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0056[ 18] = { /* code 0056 */
  X_X_X__X,
  XX_XX__X,
  XXX_X_XX,
  ____XXXX,
  __X_XX__,
  _XX_X___,
  X___X_X_,
  _X__XX__,
  __X___X_,
  XX____X_,
  _X__X_X_,
  ____X_XX,
  ___XX_XX,
  __XXXXX_,
  ___XXXXX,
  XX__XX_X,
  X_______,
  _XX_X___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0057[ 18] = { /* code 0057 */
  X_X___XX,
  _X____X_,
  X_XXX___,
  X___X___,
  _XXX_XX_,
  __X_____,
  __X_X_X_,
  _XXX__XX,
  ____XXX_,
  _XXX__X_,
  X__X_XXX,
  X_XX___X,
  ____XX__,
  _XX_X_XX,
  __XXX_X_,
  X_____X_,
  XXXXXXXX,
  X____XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0058[ 18] = { /* code 0058 */
  __XX_XX_,
  XX_X_XXX,
  XX_XX__X,
  XX____X_,
  _X__XX__,
  XXXX__X_,
  _XXXXX__,
  _XXX_X__,
  X_XX_XXX,
  __XXXXXX,
  X__X__XX,
  X___X__X,
  ___XXX_X,
  _X___XXX,
  _XX__XX_,
  XX__X_X_,
  _XXXX_X_,
  ___X_XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0059[ 18] = { /* code 0059 */
  _X___X_X,
  _XX_X_X_,
  _X__XX__,
  _X_X_XXX,
  __XXXX_X,
  _____XXX,
  _XXX__X_,
  X__X___X,
  X_______,
  __X_X_XX,
  X_____XX,
  _____XXX,
  __XX____,
  ___XXX_X,
  _X_X___X,
  ___XX__X,
  XX_XXXX_,
  XXXXX__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_005A[ 18] = { /* code 005A */
  _XXXX_X_,
  _X_XX__X,
  X____X_X,
  X______X,
  _____X__,
  XX_XXXXX,
  _XX___XX,
  __XX____,
  X____X__,
  ___X__XX,
  __X_____,
  XX______,
  __X_X___,
  XXXXX__X,
  _X___XX_,
  XX___XXX,
  XXX_____,
  XXX_XX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_005B[ 18] = { /* code 005B */
  X____X_X,
  _XXX____,
  XX_XX_XX,
  X_XX__X_,
  _XXX____,
  ___XXXX_,
  ___XX_XX,
  _X_XXX_X,
  __XX_X__,
  ___X__X_,
  _X_____X,
  XX___XX_,
  XXX_XX_X,
  __XX___X,
  ___XXXX_,
  X_X_XXXX,
  X_XXXXXX,
  XXXX__X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_005C[ 18] = { /* code 005C */
  XXX_X__X,
  XXXXXXXX,
  __X_XXXX,
  _XX__X__,
  X_XX_XX_,
  XX_XX_X_,
  X_X_X__X,
  _X_X__X_,
  __XXXX_X,
  __X__XX_,
  _XXXX__X,
  ___X_X_X,
  X_X__XX_,
  XX__X__X,
  XXXX_XX_,
  X__XX__X,
  _____XX_,
  X_XX__X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_005D[ 18] = { /* code 005D */
  __XXXX__,
  _X____X_,
  _X__X_X_,
  X__XX___,
  XXXX_XX_,
  X__X__X_,
  X____XXX,
  __XXX__X,
  XXXXXXX_,
  X__X_XX_,
  XX_X___X,
  X____XXX,
  ____XXX_,
  X__X_XXX,
  _XXX_X_X,
  XXXXXXX_,
  XX_X__XX,
  _X_X__XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_005E[ 18] = { /* code 005E */
  __X_XXXX,
  X___XX_X,
  XXXXXXXX,
  XXXXX_X_,
  _X_X_XXX,
  XXXXX__X,
  __XXX_X_,
  X_XXXXX_,
  XX______,
  __XX__X_,
  _X__X_XX,
  XXX_XXX_,
  __X_XX__,
  XX_X__X_,
  XX_X____,
  _X_X_XX_,
  XXXX___X,
  X_X____X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_005F[ 18] = { /* code 005F */
  X_XXX_XX,
  ___XX___,
  XX_X_X_X,
  XXX__XXX,
  XX_XX__X,
  _XXXXX_X,
  X_XX_XXX,
  ___X___X,
  XXXX_X__,
  _XX_X_X_,
  ___XXX__,
  XX_XXXX_,
  ___XX_XX,
  ___X__XX,
  X_XX_XX_,
  _____X__,
  __XXX_X_,
  XXXX_X__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0060[ 18] = { /* code 0060 */
  _X_____X,
  _X___XXX,
  ____X__X,
  _XXX_X__,
  __XXXXX_,
  __XX_X__,
  _XXX___X,
  X__XX_XX,
  X__X___X,
  XXXX__XX,
  ____X___,
  X_XX_XXX,
  _XX_____,
  XXX__XX_,
  X_XXXX_X,
  ______X_,
  XX___XX_,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0061[ 18] = { /* code 0061 */
  XX__X_X_,
  XXX__XXX,
  XX_XX_XX,
  _XXXX__X,
  XX___X_X,
  ___XXX_X,
  X_XX___X,
  X_XXX_X_,
  XXXX_XXX,
  __X_XXX_,
  X____X_X,
  _X_X__XX,
  ___X_X__,
  _XXXXX__,
  X_____XX,
  X__XX___,
  X__XXXX_,
  XX_XX_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0062[ 18] = { /* code 0062 */
  _X_XX_XX,
  X___XX__,
  X_______,
  _XX__XX_,
  _XXXXX__,
  XXXX__XX,
  XXX__X__,
  X_X___XX,
  _XX_XX_X,
  __XXXXXX,
  _XXX____,
  X___X_X_,
  X_X___X_,
  X____XXX,
  X_XXX__X,
  ____XX__,
  ___XXX_X,
  XX__XXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0063[ 18] = { /* code 0063 */
  _XX_X_X_,
  _XX_X___,
  ____X_XX,
  X_XXX__X,
  ____X_XX,
  _XXXX_X_,
  ____XX__,
  X_XXX_X_,
  XX_X____,
  XXX_XXX_,
  XX_X_XX_,
  _X___XXX,
  X__XXX_X,
  X_X_X__X,
  ___X_X_X,
  __X_X_X_,
  X_X_X_X_,
  _____X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0064[ 18] = { /* code 0064 */
  XX_X_X__,
  XX_X__XX,
  _XX_X___,
  XX_X_X__,
  XXXX_X_X,
  _XXXX__X,
  __X__XX_,
  ____XX__,
  X_XX____,
  _X_XX_X_,
  X_XX_XX_,
  ____X_X_,
  _XXXXXXX,
  XXX__X__,
  ___X__X_,
  X___X___,
  XXX__XX_,
  X__XX__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0065[ 18] = { /* code 0065 */
  X_____XX,
  XXX_XXX_,
  XX_X_X__,
  X_X_XXX_,
  X__XXXXX,
  XXX__X__,
  XX___X__,
  X_XXX_XX,
  X_X_XXX_,
  __X___X_,
  XXXX_XXX,
  _X_X__X_,
  ___XX_XX,
  _X_X___X,
  ____X_XX,
  __XX__X_,
  X__X___X,
  XX_XXX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0066[ 18] = { /* code 0066 */
  _X___XX_,
  XXX__X__,
  X_X___XX,
  _____XX_,
  _XX_XXXX,
  X____X__,
  X____X_X,
  XXX____X,
  ___X____,
  _X_X____,
  X______X,
  XX_X_XXX,
  _XX___XX,
  X_XXX__X,
  _XX_XXXX,
  X___XXXX,
  _X___X_X,
  XXX__X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0067[ 18] = { /* code 0067 */
  ___XXXXX,
  _XX_X___,
  X_X__XX_,
  _XX__X__,
  X_XXX__X,
  XX__XXXX,
  X__X__XX,
  XXXX____,
  _X_____X,
  X_X__X__,
  __X_X_X_,
  __XX__X_,
  _X_XXX_X,
  X___X__X,
  _X_XXXXX,
  X_X__X_X,
  XXX_X__X,
  X_XXXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0068[ 18] = { /* code 0068 */
  __X_XX_X,
  __XXX_XX,
  X____XX_,
  _X_XX__X,
  XXX__X__,
  X_XXX_X_,
  X_XXX__X,
  X_X___X_,
  ___XX_X_,
  X_XXX___,
  X_XX__XX,
  XX_X__XX,
  _XXXXXX_,
  __XX____,
  _X_XX___,
  XXX___XX,
  X_XX___X,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0069[ 18] = { /* code 0069 */
  XX_XX_X_,
  _X___X_X,
  XX_XXX_X,
  XX__XXXX,
  XXXXXX__,
  XX_XX_XX,
  X__X_XX_,
  ___X__X_,
  X_XXX__X,
  __XXXX_X,
  XX___XX_,
  _X_XX_X_,
  __X_XXX_,
  __XXXX__,
  __XXXXXX,
  _XX__X__,
  X_XX____,
  X__X_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_006A[ 18] = { /* code 006A */
  X_X___X_,
  X_X_XXX_,
  _X__X_X_,
  _X_X_XXX,
  X_XX_X__,
  XX_XX___,
  _X_X__XX,
  XXX__X__,
  XXX_XXXX,
  _XXXX_XX,
  ___X_X__,
  XXXX___X,
  _XX____X,
  X____X_X,
  XX__X___,
  XXXXXXX_,
  X_XXX_X_,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_006B[ 18] = { /* code 006B */
  _X__XX_X,
  X_X_XXX_,
  _XXXX_XX,
  __XX___X,
  _XX____X,
  _XX_X__X,
  _XXX_X_X,
  _X_XX_XX,
  __X_X_X_,
  __XX__X_,
  _X_XX_X_,
  X_XXX_X_,
  X_X___XX,
  __XX_X_X,
  X___XX__,
  _____X__,
  _XXX__X_,
  __XX____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_006C[ 18] = { /* code 006C */
  ____XX_X,
  XXXXX___,
  X___XXXX,
  X_XX_X__,
  _XXX__X_,
  XXX_XXX_,
  X_____XX,
  _XXXX__X,
  __X_XXXX,
  _X_XX_X_,
  XXXX_XXX,
  ___XXX__,
  ___XXX__,
  X_XX___X,
  __XX_XXX,
  _X__XXXX,
  XX_X__X_,
  __XX___X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_006D[ 18] = { /* code 006D */
  X___XX_X,
  _X______,
  XXX_XX__,
  _____X__,
  XXX__X__,
  X_XXX_X_,
  _X__X___,
  _X___X_X,
  X_X_____,
  _XXXXXXX,
  XXX_X_X_,
  _XXXX_XX,
  XX__X__X,
  _X__X__X,
  XX______,
  XXXXX__X,
  _XX___XX,
  X_XX___X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_006E[ 18] = { /* code 006E */
  _X__X_X_,
  X___XXX_,
  XX__XXXX,
  XXXX__XX,
  __XXXX__,
  X____X_X,
  XXXX_X__,
  ___X__XX,
  _X_X____,
  X__X___X,
  X____XX_,
  __XXX___,
  ____XX__,
  _X_X___X,
  _XXX_X_X,
  ___X_XX_,
  X_XX_X__,
  XX___X__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_006F[ 18] = { /* code 006F */
  X_X____X,
  __X_____,
  X__XXXX_,
  X__XX_X_,
  XX_X_XXX,
  XX___X__,
  __X_XXXX,
  XX_XX_XX,
  X_XXXX_X,
  X_XXXX__,
  _XX_XX__,
  XX_XX__X,
  X_X_X_XX,
  _X__XX_X,
  XX_XX__X,
  _X_X___X,
  _X__X___,
  X_XXXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0070[ 18] = { /* code 0070 */
  _X_XXXX_,
  __XXX_XX,
  XX___XXX,
  XXXXX__X,
  __X__XX_,
  __X_XXXX,
  X_XXXX__,
  _X___X_X,
  __X__X_X,
  _XXX___X,
  XXXXX__X,
  __X___XX,
  ___X_X_X,
  X__XX__X,
  X_X_XXXX,
  __X_____,
  XX_XXX_X,
  _____X__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0071[ 18] = { /* code 0071 */
  XX___X__,
  ____X_X_,
  _X_____X,
  XXX__X_X,
  ___X_XX_,
  XX__X_XX,
  ___X_XXX,
  X_XXX__X,
  ___X_XXX,
  _X_XX__X,
  _X_X____,
  _X_X_X__,
  ____XX__,
  __X_XX_X,
  _X__X___,
  XXX__X__,
  XX______,
  _XX___X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0072[ 18] = { /* code 0072 */
  XX______,
  _X__XX__,
  _X_X_X_X,
  X_XX____,
  X___X___,
  _XXX____,
  ___X_X_X,
  _XXX__XX,
  X___XXX_,
  ___XX_X_,
  _XXXXXX_,
  X_X_X_X_,
  XX_____X,
  XXXXX_XX,
  _XX__XXX,
  X_X_X__X,
  __X__XXX,
  _X___X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0073[ 18] = { /* code 0073 */
  XXX_XXXX,
  X_X__XX_,
  X_XX__X_,
  __XXX_XX,
  XX_XX_XX,
  __X_X___,
  _X__X__X,
  ____XXXX,
  XX___XX_,
  X____XXX,
  X__XX__X,
  __XXXXXX,
  XXXX__XX,
  X____XXX,
  X_X_XXXX,
  XXXX____,
  _XX___XX,
  XX_X_XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0074[ 18] = { /* code 0074 */
  _XXXXX_X,
  _X_X____,
  XX__XX_X,
  XXXXXXX_,
  X__XXXXX,
  _XX__XXX,
  __XXX___,
  __X__X__,
  X_X___XX,
  __X_____,
  _XXXX___,
  _X_____X,
  XXX_X_XX,
  X__XXXXX,
  XX_XXX_X,
  _X_X_XXX,
  ___XX_X_,
  ___XX_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0075[ 18] = { /* code 0075 */
  __XX__X_,
  __X_XXX_,
  XXXXX___,
  XX__X_X_,
  XX____XX,
  X___XX_X,
  XX_XXXXX,
  XX____X_,
  X_X_____,
  ____XX_X,
  XXX_X_XX,
  XXXX__X_,
  X__XX_X_,
  X_X__XX_,
  XX_X_XXX,
  __XX____,
  __X____X,
  X___X_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0076[ 18] = { /* code 0076 */
  ______X_,
  X_X__X__,
  X__X_X_X,
  __XXXX_X,
  X_XX____,
  XXXXXX__,
  _X_XX_XX,
  XX_XXXX_,
  X__XXX_X,
  X_XXX___,
  _XX__X__,
  _XX_____,
  XX___XXX,
  __XXX_X_,
  XX__XXX_,
  _X_XX_XX,
  _XX___X_,
  X__X__XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0077[ 18] = { /* code 0077 */
  _____X_X,
  _____X_X,
  XX__XX_X,
  ___XXX__,
  X_X__XXX,
  _XX__XX_,
  _____X_X,
  ____XXX_,
  X_X_____,
  ___XX__X,
  ____X_X_,
  __XX___X,
  XXX_XX_X,
  X__XXXXX,
  X_XXX_X_,
  XXXXX___,
  XX_X__XX,
  X_XXXXXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0078[ 18] = { /* code 0078 */
  _XX__XX_,
  _X____XX,
  _X__X_X_,
  X_XX_X_X,
  XXXXXXX_,
  ________,
  ___X_XX_,
  ___X_X_X,
  _XX_X_X_,
  __XXX_X_,
  ______X_,
  XX____XX,
  X_XXX_XX,
  __XX_X_X,
  _X__X___,
  X__X__XX,
  X_XX_XXX,
  X_____XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_0079[ 18] = { /* code 0079 */
  X__X_XX_,
  XX_XXX__,
  _XX__XXX,
  X_X_XX__,
  ___X___X,
  _XX_XX__,
  __X___XX,
  ___X_X_X,
  ___XXX_X,
  XXX_XXXX,
  X_X_X__X,
  XXXXX__X,
  ___XXXXX,
  __XX_X_X,
  __X__XX_,
  X__XXX__,
  _XXXXX_X,
  __XX_XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_007A[ 18] = { /* code 007A */
  ___X____,
  __X__XX_,
  X_X_X_XX,
  XXXXX_X_,
  ___X____,
  _X_XX_XX,
  XXX___X_,
  X__X_XX_,
  X___X_X_,
  _XX_XX__,
  _X_XXXX_,
  ___XX_XX,
  X_XX__X_,
  _XXXXX__,
  X____X_X,
  ___XX_XX,
  __X____X,
  X__X__XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_007B[ 18] = { /* code 007B */
  XXX_X_X_,
  __X_X__X,
  X___XXXX,
  __XX_X_X,
  XX_X___X,
  X_X____X,
  __XX____,
  __X__XX_,
  ___XX___,
  __XXXX_X,
  __XX____,
  _X____X_,
  __XXXXX_,
  X__XXX__,
  _X_X_X__,
  XX_XXXX_,
  X__X___X,
  X_X_XXXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_007C[ 18] = { /* code 007C */
  X_XXXX_X,
  _XXXX_XX,
  _XXXXXX_,
  X_XX__X_,
  ___X___X,
  X_X_X__X,
  X__X__XX,
  ___X___X,
  _XX_____,
  X_X___X_,
  X_X_X_X_,
  X_XX___X,
  XX__XX__,
  __XX__XX,
  XX_XX_X_,
  XX_XX_X_,
  _XXX_X__,
  _XXX_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_007D[ 18] = { /* code 007D */
  _XX_XX_X,
  X_XX_X__,
  X___X__X,
  _X___XXX,
  XX_XX___,
  X_X___XX,
  _X____XX,
  X_XXXX_X,
  ____XX_X,
  _XX___X_,
  __XX__X_,
  XXXXX___,
  _XX_____,
  XX_XXXX_,
  ___X_X__,
  _XXXX_XX,
  X__X__X_,
  XXX__XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_007E[ 18] = { /* code 007E */
  X_______,
  XXXX__X_,
  XX_X___X,
  X__X__XX,
  __X__XX_,
  _XXXXX_X,
  X_XXX__X,
  _XXXX_X_,
  XXXXX_X_,
  _XX_X__X,
  _XXX_X_X,
  X_X__XXX,
  XX_XX__X,
  XX_X_XX_,
  X_X__X_X,
  _X___X__,
  X__XX___,
  XX_XX___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_007F[ 18] = { /* code 007F */
  X__X_XXX,
  _______X,
  _X__X__X,
  _XX___X_,
  ___XX_X_,
  XXX_X__X,
  ___XXX__,
  _XX___X_,
  _X__X_X_,
  __X_X___,
  XX__X___,
  _X_XX_X_,
  XX__X_X_,
  XX_XXXXX,
  X___XX_X,
  XXXX_XXX,
  _X_X_XX_,
  ____XXXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A0[ 18] = { /* code 00A0 */
  __XX_X_X,
  XX____X_,
  XX_XX_X_,
  XX___XXX,
  X__XXX__,
  XX__XXXX,
  ____XX_X,
  XX_X__XX,
  ___XXX_X,
  XXXX_XX_,
  XX__X__X,
  _X_X___X,
  _X_X__X_,
  X__XXX_X,
  ______XX,
  ____X__X,
  ___XXXXX,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A1[ 18] = { /* code 00A1 */
  ___XX__X,
  _______X,
  XX_XX_XX,
  X____XXX,
  XXXXX_XX,
  _X___X_X,
  _XX_X_XX,
  __XXX_X_,
  __X__XX_,
  X___X__X,
  __XX_X_X,
  __X_XX_X,
  ___XX_X_,
  _____X_X,
  _X_____X,
  X__XXX__,
  XX__XX_X,
  X____X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A2[ 18] = { /* code 00A2 */
  XX_X____,
  XXXX_XXX,
  X_XXXXX_,
  X_XX_X__,
  __X__X__,
  XXXX_XXX,
  __XX_X_X,
  __XXXX_X,
  XX__X_XX,
  _X___X_X,
  _X___X__,
  X_____XX,
  XX_XXXX_,
  X_____XX,
  __X_X_X_,
  ___X_XX_,
  X_XXXXXX,
  X_XXXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A3[ 18] = { /* code 00A3 */
  ______X_,
  __XX____,
  ___X_XX_,
  __XXX_X_,
  XXX_X___,
  ____XX__,
  X_X__XX_,
  _X__X___,
  XX_XXX__,
  X___XXX_,
  _X____XX,
  _X____XX,
  _XXXXXX_,
  __X_XXX_,
  __XX_XX_,
  _X_X___X,
  X____XX_,
  _X_____X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A4[ 18] = { /* code 00A4 */
  X___X__X,
  XX_X_XXX,
  XXXXXX__,
  __X_X___,
  _XXXX_X_,
  ______X_,
  _X__X___,
  ___XXX_X,
  XXX_X___,
  _X_XXX__,
  __X__X_X,
  XXXXXX__,
  XX_X___X,
  ___XX_XX,
  __XXXX__,
  _X___XXX,
  X_XXX_XX,
  ___XX__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A5[ 18] = { /* code 00A5 */
  ___X____,
  _XXXXX__,
  X_XXXXXX,
  XX_X___X,
  XX_X___X,
  ____XXX_,
  ___XX___,
  X_XXXX__,
  _XXXXX_X,
  XX___X__,
  _X_X____,
  X_X_X___,
  _XXX_X_X,
  __XXX___,
  _XXX__XX,
  X_XX_XXX,
  ___X____,
  _X_XX___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A6[ 18] = { /* code 00A6 */
  _XX____X,
  ___XX_XX,
  X___XXXX,
  ___XXX_X,
  X_XXX_X_,
  X______X,
  _X_X_XX_,
  _XXX_XXX,
  __X__XXX,
  __X___XX,
  X___XX_X,
  X_XX_XX_,
  ___X__XX,
  __XXX__X,
  XX_XXX__,
  _XX____X,
  _____XX_,
  X__X_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A7[ 18] = { /* code 00A7 */
  _____XXX,
  _____X__,
  XX_XXXX_,
  _XX_____,
  _X__X_X_,
  _X_XX_XX,
  ___XXXXX,
  X___XXX_,
  _X__XX_X,
  _X__XXXX,
  XXXXXXX_,
  X_XX_XX_,
  X___XX__,
  XX__XXX_,
  XXXX____,
  XXXXXX__,
  XX____XX,
  X__X_XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A8[ 18] = { /* code 00A8 */
  X_XXX__X,
  __XXXXXX,
  _X___X__,
  X__XXX__,
  _XX_X_XX,
  XX___X_X,
  XXXX_XXX,
  XX_XX_XX,
  XX__XX__,
  __XXX__X,
  _XXX____,
  ___X_X_X,
  X__X_XXX,
  _X__XXXX,
  _X___XX_,
  X_XXX_X_,
  XXX_XX__,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00A9[ 18] = { /* code 00A9 */
  _X_XX___,
  XXXXX__X,
  XXXXX_XX,
  ___X_X__,
  XXXX_XX_,
  X_X_X_X_,
  ___X__XX,
  X__X_XX_,
  _XX_XX__,
  X___X_XX,
  _X__XX__,
  X_X__X_X,
  _X_____X,
  ___XXXXX,
  XXX_XX_X,
  XXX_____,
  _XX___XX,
  __X_X_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00AA[ 18] = { /* code 00AA */
  ____XX_X,
  XX_XXX__,
  _X___XX_,
  X_X_XX__,
  _XX__X_X,
  XX_XX___,
  X_X_____,
  _X_X____,
  _X__XX_X,
  ____X___,
  XXX_X___,
  __XX__X_,
  X_XXX__X,
  __X_____,
  _XXX__XX,
  __XX__X_,
  X__X_X_X,
  _XXX____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00AB[ 18] = { /* code 00AB */
  ______XX,
  XX_X_XXX,
  __X_X_XX,
  X_XX_XX_,
  X_XX____,
  X_XX__XX,
  _X_X_X_X,
  __X____X,
  _____X__,
  _____X_X,
  __XX_XXX,
  __XXXXXX,
  _XXX____,
  _XX____X,
  XXX_XXX_,
  _XXXXXX_,
  _XXXXX__,
  _X_XX__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00AC[ 18] = { /* code 00AC */
  ____X__X,
  XXXXX___,
  _X__XX__,
  _XX_____,
  _XXX_X__,
  ___X_X__,
  X_X_XX_X,
  __XX____,
  X_XXX_XX,
  XX_XXXX_,
  __X__X__,
  ___XXXXX,
  XXX__XXX,
  XX__X_X_,
  __X_X__X,
  X_X_____,
  X____X__,
  XXXXXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00AD[ 18] = { /* code 00AD */
  _X_XXX__,
  XXX__XX_,
  XX___XX_,
  _XXXX_X_,
  XX__X_X_,
  X_____XX,
  ___X____,
  XXX____X,
  _X____XX,
  XX__X__X,
  X_X_____,
  X_______,
  X__X_X_X,
  __X_X___,
  X_XXXX__,
  XXXXX___,
  X_XX____,
  X_XXXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00AE[ 18] = { /* code 00AE */
  XXX__X_X,
  XXXX_X_X,
  XXX___XX,
  X_XXX_X_,
  XXX_X__X,
  _______X,
  __X__XXX,
  XXX__X_X,
  __X____X,
  XXX_XXXX,
  X__X____,
  _X_X___X,
  _XX__X_X,
  XX_XXX_X,
  X__X_X__,
  XX_X__X_,
  _X__XXXX,
  X_XXXXXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00AF[ 18] = { /* code 00AF */
  XX_XXXXX,
  _X__X_XX,
  _X____X_,
  ___XXXX_,
  _X___X__,
  _____XX_,
  XX___X__,
  X_X_____,
  X_____XX,
  _X___XXX,
  _X_X_X_X,
  XX_XX__X,
  _XXXX___,
  X_X_X_XX,
  _XX_XXX_,
  X_X_X_X_,
  _XX__XX_,
  __X___X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B0[ 18] = { /* code 00B0 */
  __XXXXXX,
  X__XXXX_,
  ___X____,
  _XX_XXX_,
  ____XX__,
  _X_X_X_X,
  XX____X_,
  ___X_X__,
  XXXXX___,
  XXXXXX_X,
  _XX_X___,
  X__X_XXX,
  _XXX_XX_,
  XXX__X__,
  ___X___X,
  _X______,
  _X___XX_,
  X______X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B1[ 18] = { /* code 00B1 */
  _XXX_XXX,
  X_XX_X__,
  XXX___X_,
  ___XXXX_,
  __XXX_X_,
  X__X__X_,
  XX__X_XX,
  X_XXX__X,
  X__X_X__,
  XX__X_XX,
  _XXXXXXX,
  __X_X_XX,
  __X_____,
  __X_XX__,
  ___XXXX_,
  _XX_____,
  ______XX,
  X___XX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B2[ 18] = { /* code 00B2 */
  _XX_X_X_,
  X_XXX_XX,
  _XXXX_XX,
  _XX_X_XX,
  ___X_X__,
  XXXXXX_X,
  X_X__X__,
  ____XXXX,
  X_X__XXX,
  XX_____X,
  _X_X_X__,
  XX_X__X_,
  ___X_X__,
  _X_XXXXX,
  __X_X___,
  _X_XXXXX,
  __X_XX__,
  __XXXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B3[ 18] = { /* code 00B3 */
  _X_____X,
  XXX__X_X,
  _XX___X_,
  X_XXXX_X,
  ____X__X,
  XX_XXXX_,
  XX____XX,
  _XXX_X__,
  XXX_X___,
  X_X_XXX_,
  _X______,
  X_XXXXXX,
  __X_____,
  ______XX,
  __X_XX__,
  X_X_X_XX,
  _X__X__X,
  X__XXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B4[ 18] = { /* code 00B4 */
  __X_XXXX,
  XX__XX__,
  ____XX__,
  _XXXX__X,
  __XXXX_X,
  ___X____,
  _X_X_XX_,
  _XXXX_X_,
  XX___XXX,
  X_X_____,
  ____X_XX,
  XX_X_X__,
  _X_XX_XX,
  XXX____X,
  XXXX___X,
  X__X____,
  ____XXXX,
  X__XXXXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B5[ 18] = { /* code 00B5 */
  XXX____X,
  X_X___X_,
  _X_XX_X_,
  X_XX_X__,
  XXXXXXXX,
  __X__XX_,
  _X____X_,
  _XX_____,
  __XX_XXX,
  _XXXX__X,
  XX______,
  _____X_X,
  X_XX_X__,
  XXX_XX_X,
  X_____X_,
  __X_XX__,
  XXXX____,
  _XX_XX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B6[ 18] = { /* code 00B6 */
  X____X__,
  _X_XXXX_,
  X__XX_XX,
  _XXX_X__,
  XXX____X,
  _XXXXXXX,
  X__XX___,
  X_XXX_X_,
  __XXXXXX,
  _X____XX,
  _X__X_X_,
  _XXXX__X,
  X_XX__XX,
  X_XXXXX_,
  __X_XX_X,
  __XX_XXX,
  _X__X__X,
  XXX_X__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B7[ 18] = { /* code 00B7 */
  __XXX_XX,
  __XXXX__,
  ___X___X,
  X__XXX_X,
  _X___X__,
  XXXX__X_,
  X_X__XX_,
  _XXX_X_X,
  X___XX__,
  X___X___,
  _XX_X_X_,
  __X_XX__,
  __XXXX__,
  ____XX__,
  X__X_X_X,
  X___X_XX,
  XX_XXX_X,
  XXXXXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B8[ 18] = { /* code 00B8 */
  X_XX__XX,
  XXX___XX,
  X__XXXXX,
  __X_X__X,
  XX_X___X,
  _XXXXXXX,
  __XXX_X_,
  ____XXX_,
  _X_XX___,
  X_XXXXX_,
  XX_XX__X,
  _XXX_XXX,
  XXXX____,
  XX__X_X_,
  __XX_X__,
  X_XX____,
  XX___X_X,
  X_____XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00B9[ 18] = { /* code 00B9 */
  _X___XXX,
  ___X_XX_,
  XXX____X,
  XX_XXXX_,
  __XXXXXX,
  _XXX_X_X,
  XXXX_XXX,
  ____XX_X,
  XX_XXX__,
  _X_X___X,
  ____XXX_,
  X_____X_,
  _X_X__XX,
  _XX_XXX_,
  X_X_XXX_,
  X__XXX__,
  X_X_XX__,
  X______X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00BA[ 18] = { /* code 00BA */
  X__X_XXX,
  XX_XXX_X,
  X__X___X,
  _XXXX_XX,
  XX_XXX_X,
  XX_XXXX_,
  ___X___X,
  _X_____X,
  _XX_X__X,
  ___X_XXX,
  XXXX____,
  __XX__X_,
  XXX__XXX,
  _X_XXX__,
  _XXXX___,
  X_XXXX_X,
  ___XXXXX,
  XXX_X___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00BB[ 18] = { /* code 00BB */
  _X_X_XX_,
  ______XX,
  ___X__X_,
  __X_XX_X,
  ________,
  _XX__X_X,
  X_XXXXXX,
  _X_X_X_X,
  ___X_XX_,
  XXX__X__,
  XXX_XX__,
  _X____XX,
  X_XXXXXX,
  _X__XXX_,
  XXXXX__X,
  X_X____X,
  X_X_XX_X,
  X____XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00BC[ 18] = { /* code 00BC */
  _XX__X__,
  XXXXXXXX,
  XXX_XX_X,
  ___X_X__,
  X_XXX__X,
  _X_X_X__,
  X_XXXXXX,
  __XXX___,
  X_XX____,
  X_X___XX,
  _XXXX_XX,
  _XX__XX_,
  _XXXX_XX,
  _X______,
  XXX__X__,
  _XXX_XX_,
  __X_X___,
  _XX_XX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00BD[ 18] = { /* code 00BD */
  XXX_XX__,
  X_XX____,
  X_XX__XX,
  __XXXX__,
  XX______,
  XXX_X_X_,
  __XXXXX_,
  X__XXX_X,
  XX_XX___,
  XXX__X__,
  ___XXX__,
  ______X_,
  _X_XXXX_,
  XXXX____,
  ____X___,
  XXXXXXXX,
  __X__X_X,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00BE[ 18] = { /* code 00BE */
  X_XX__X_,
  X___X___,
  X_XXX_XX,
  X______X,
  X_X___X_,
  _XXXXX_X,
  _X__X___,
  XX__XX__,
  ___X_X_X,
  X__X_XX_,
  ___XXX_X,
  X__X_XXX,
  X____X_X,
  _X__XXX_,
  _XXX_X__,
  X_XX____,
  __X_X_X_,
  __X_X_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00BF[ 18] = { /* code 00BF */
  XXX_X__X,
  _XX___X_,
  ___XX__X,
  _XX___X_,
  XX__X_XX,
  ___X_XXX,
  _X_XXXX_,
  ___XXX__,
  _XX__XX_,
  X__X___X,
  X_XX__XX,
  XX_XXXXX,
  X___X__X,
  _XX_X__X,
  ____X_XX,
  X___X__X,
  _XXXX__X,
  ____X_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C0[ 18] = { /* code 00C0 */
  XXX_X___,
  XXX___X_,
  _X_XXXXX,
  X___X_XX,
  XX_X_XXX,
  X_XXXXX_,
  __X___XX,
  XXX_X___,
  _XX_XX__,
  _XX_XXX_,
  X__XX___,
  XX__XXX_,
  X_XXX__X,
  XXX___XX,
  __X_XXXX,
  XXXX____,
  _X__X__X,
  XXXXXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C1[ 18] = { /* code 00C1 */
  XXXXX___,
  ___XXX__,
  __XX____,
  XXXXXX__,
  X__X_X_X,
  _XX__X__,
  _XXXXXX_,
  X_XXXXX_,
  _XXX_X_X,
  XX_XXX_X,
  X__XX_X_,
  _X_X_XX_,
  __XX_X__,
  ____XX_X,
  __XXXX_X,
  ___XXX_X,
  _X_XXX__,
  __X____X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C2[ 18] = { /* code 00C2 */
  X_XX____,
  ____X__X,
  X__X__X_,
  X__XXX_X,
  XXXX____,
  _XX_XXX_,
  XX_X_X_X,
  XX_XX_XX,
  X_______,
  X_XX_XX_,
  _XX_X_X_,
  XXXXX___,
  _X_XXXXX,
  __X___XX,
  XXXX_XXX,
  XXXX__X_,
  _____X__,
  _X____X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C3[ 18] = { /* code 00C3 */
  X_X_XX__,
  ___XX_XX,
  XX_X__X_,
  __XXXXX_,
  __XXXX_X,
  X___X___,
  X_____XX,
  __XX_XXX,
  X_X___X_,
  X____X_X,
  ___XXXXX,
  XX____XX,
  __X_XXXX,
  XX_XX_X_,
  X__XXX__,
  __X___XX,
  XXX_X___,
  _XX_X___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C4[ 18] = { /* code 00C4 */
  ___XX_XX,
  _X__XXXX,
  __X_XX_X,
  X_X_X_XX,
  ___XX__X,
  _XXXXX_X,
  XXX__X__,
  _XXX__X_,
  ___XXX__,
  XX_XXX__,
  XX___X__,
  _XXXX__X,
  XXX___X_,
  _XX___X_,
  ___X_XX_,
  _XX_XXX_,
  _XX_X_XX,
  ___XXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C5[ 18] = { /* code 00C5 */
  XX_X___X,
  X_______,
  __XX___X,
  __X_X___,
  XXX_XXXX,
  ___XXXXX,
  _X__X__X,
  ___XXX__,
  __XXX___,
  _X_X_XX_,
  XX_XX_X_,
  XX_X_XXX,
  _X_XX__X,
  ____XXXX,
  __XX_XX_,
  __X_XXXX,
  XXX____X,
  __X_XXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C6[ 18] = { /* code 00C6 */
  XX__X__X,
  _XX_X___,
  X_X____X,
  XXXXXX__,
  X____XX_,
  _____XXX,
  XX___XX_,
  X______X,
  X_X_XX_X,
  XX_XX__X,
  XXX___XX,
  X_X_XXXX,
  _____XX_,
  __XXXX_X,
  ____XX_X,
  XXXX_XX_,
  X_X_XX__,
  XXX_XX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C7[ 18] = { /* code 00C7 */
  __X_X__X,
  ___XXX_X,
  _X_XX_XX,
  XXX__XXX,
  X__XX_X_,
  X_XX_X_X,
  __XXXX__,
  XXXXXX_X,
  _XX___X_,
  _X_X_XX_,
  X_____XX,
  __X_XXXX,
  ____XX_X,
  _X_X__X_,
  _XXX__X_,
  X_____X_,
  XXX_XXXX,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C8[ 18] = { /* code 00C8 */
  XXX___X_,
  X__XX_X_,
  XXXX___X,
  __X__XX_,
  XX__X_XX,
  X_XXXXXX,
  XX__X__X,
  XX_XX___,
  X_X__X__,
  __XXXX_X,
  XXX_XX_X,
  XXX___XX,
  X_XX_X_X,
  X_XX_X_X,
  __X_XX__,
  X__X_X_X,
  ___XXXX_,
  _XXXX_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00C9[ 18] = { /* code 00C9 */
  X___X__X,
  __XXXXX_,
  _X_X__X_,
  _XX_X__X,
  X___X_X_,
  X_X___XX,
  _XX_X_XX,
  ____XXX_,
  XX_XXX_X,
  _X___XXX,
  _XX_X_XX,
  XX_X_XXX,
  _XXXXXXX,
  _X___XX_,
  X_XX____,
  _XX__X__,
  X_X___X_,
  _XX_XX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00CA[ 18] = { /* code 00CA */
  __X_XXXX,
  __X__XXX,
  _XXX____,
  X_X__X_X,
  _XXXX__X,
  _X_XXX_X,
  _XXX___X,
  X__X__XX,
  _____XX_,
  _XXX__X_,
  XXX__XX_,
  ___XX_XX,
  X___XX__,
  X_X__X__,
  X_XX_XX_,
  _____X__,
  __X__XXX,
  X_____XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00CB[ 18] = { /* code 00CB */
  X_XXXX_X,
  XX_X_X__,
  XXXX_X__,
  __X_XXX_,
  _XXX___X,
  ___X_XXX,
  XXXXX_X_,
  XX_XXXX_,
  __XXX___,
  XX__XX_X,
  X_X__XXX,
  X_XXX_XX,
  X_X____X,
  XX___XXX,
  _XX____X,
  _______X,
  ______X_,
  _X_X____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00CC[ 18] = { /* code 00CC */
  XX_X_X__,
  _XXXXX__,
  X__XXX_X,
  _X_XXXX_,
  X___XXXX,
  _XX_X_XX,
  X_X___XX,
  _______X,
  XXXX_XX_,
  _X_XX_XX,
  X_XX_X_X,
  XX__X_XX,
  XXX____X,
  X_XX_X__,
  _____X_X,
  X_XXX__X,
  ___XXX_X,
  _XX_X_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00CD[ 18] = { /* code 00CD */
  X___XX_X,
  __XX____,
  _XXX__XX,
  ____X__X,
  X_XX_X__,
  XX___X_X,
  XXX__X_X,
  _XX__X__,
  X__X_XX_,
  ___XXX_X,
  _____XXX,
  X_XXX__X,
  X_XXX_XX,
  __XX_XXX,
  _XX_XX__,
  _XXXXX__,
  _X_X_X_X,
  _X__X_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00CE[ 18] = { /* code 00CE */
  _X_X_XX_,
  X___XX__,
  X_X__X_X,
  X______X,
  X_XX___X,
  X____X_X,
  X____XX_,
  _XX_X__X,
  X___XXXX,
  ___XXX__,
  XXXXXXX_,
  _X__X_X_,
  __XX___X,
  XX__X__X,
  _X___X_X,
  _XX__X__,
  _X_____X,
  _X______};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00CF[ 18] = { /* code 00CF */
  XXXX__XX,
  _X_X__XX,
  _XXX_XXX,
  X__XX_X_,
  X____X_X,
  X_XXX_X_,
  XXX_X__X,
  _X_XXXXX,
  X___X_X_,
  _X___XX_,
  ______XX,
  _X_XXX__,
  X_X_X__X,
  __XXXXXX,
  _X___XX_,
  XX_X_X_X,
  _XX_X_XX,
  _X__X_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D0[ 18] = { /* code 00D0 */
  X_X____X,
  ___XX_X_,
  XX_____X,
  X_____X_,
  XXX_X_XX,
  __X_X_X_,
  XX__XXX_,
  __XXXXXX,
  X___XX__,
  XXX_X__X,
  X_X_X_XX,
  XX_XXX__,
  XX_XXX__,
  X__X_XXX,
  __XXXXXX,
  XX_XX__X,
  ______X_,
  X____X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D1[ 18] = { /* code 00D1 */
  X_X__XX_,
  _XXX__XX,
  X_XXXX__,
  _XX__X__,
  _XXX_X__,
  X_XXX__X,
  X_X_X_X_,
  __XXXX_X,
  _XX__X_X,
  __X_XXXX,
  XXXXXX_X,
  X__X___X,
  __XXXXX_,
  _X___XXX,
  XXX__XXX,
  _XX__X_X,
  XXXX__X_,
  ___XXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D2[ 18] = { /* code 00D2 */
  __X__X_X,
  XX____X_,
  _XXX_X_X,
  _X__X_X_,
  _XX__X_X,
  XXX_X__X,
  _XXX_XXX,
  X___X__X,
  _X___X_X,
  X_XXX_XX,
  __XXX___,
  XX_X___X,
  _X__X___,
  _X_XX_X_,
  X_XXX__X,
  XX_XX__X,
  XX_XX_X_,
  XX______};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D3[ 18] = { /* code 00D3 */
  _X__XX_X,
  XX__XX__,
  _XXX_XXX,
  __XXXX_X,
  X___XX__,
  _X______,
  _XX__X__,
  ____X_X_,
  X__X____,
  XX_XXX_X,
  _X_X_X__,
  X_XXX_XX,
  XXX____X,
  XXXX_X_X,
  _X___XXX,
  XX_X____,
  _____X_X,
  X_X__X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D4[ 18] = { /* code 00D4 */
  XXX_X_XX,
  XX__X___,
  X__XXXXX,
  X___XX_X,
  _XXX_XX_,
  XXX_X_X_,
  XXXXXX__,
  _X_X__XX,
  _X_XXXX_,
  X_X__X__,
  XX_XX_X_,
  X_X__XX_,
  XXXX____,
  X__XX_X_,
  XXXXXXXX,
  X_X_X__X,
  XX_X__XX,
  ___XXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D5[ 18] = { /* code 00D5 */
  _XXX____,
  XX_X_X__,
  _XXX_X_X,
  _X__XXXX,
  XX_X___X,
  _XXXXXXX,
  _____XX_,
  _XX__X__,
  XXX__XX_,
  XXXXXXX_,
  _XX_____,
  _XXXXXXX,
  X_X_XXX_,
  XX_X___X,
  ___XX_X_,
  X_X_X___,
  ___X__XX,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D6[ 18] = { /* code 00D6 */
  XXX_XXXX,
  __X__X_X,
  X_XX_XXX,
  XX__XX_X,
  ___XXX_X,
  _XXXX_XX,
  XX__X__X,
  __X__X__,
  ___X_X__,
  __XXXXX_,
  X__X_XX_,
  _X_XXXXX,
  _XX_X___,
  __XXXXXX,
  XXXXXX__,
  X_X__X__,
  XX__XX__,
  X__X_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D7[ 18] = { /* code 00D7 */
  ___X_XXX,
  _XXX_XXX,
  _X______,
  X__XX_XX,
  XX_X_X_X,
  ___XXX__,
  __X_XX__,
  X___XXXX,
  X__X__XX,
  X_X_____,
  X_XX_XXX,
  X_X_X___,
  XXX_XXXX,
  XXX_____,
  __XX_XXX,
  _XXX_X__,
  X_X___XX,
  XX___X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D8[ 18] = { /* code 00D8 */
  X_X_X__X,
  XXX__X__,
  _XXXXXX_,
  XX__XXXX,
  _X_X__X_,
  _____X__,
  __X__X__,
  _XX__XX_,
  _____X_X,
  __XXXXX_,
  ___XXX__,
  X_XX___X,
  _X_XXXX_,
  X_XX___X,
  ___XX_X_,
  XXXXXX__,
  _X_X___X,
  _____XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00D9[ 18] = { /* code 00D9 */
  XX___XX_,
  X_X___XX,
  XX_XX_X_,
  X_X____X,
  _X_____X,
  ___X_XXX,
  X___X_XX,
  X___X___,
  __X_XXXX,
  X__X_XXX,
  X____XX_,
  XXXXX_XX,
  _XX__X_X,
  _X__XXXX,
  XXXXX_XX,
  ___XX___,
  _XXXXX_X,
  _X___X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00DA[ 18] = { /* code 00DA */
  __XXXX_X,
  X_X_X_XX,
  X_XXXX_X,
  ___X__XX,
  X_X_XX_X,
  XX_XXXX_,
  XX______,
  XXXXXX_X,
  _X_X__XX,
  XXX_____,
  XX_XXX__,
  _XX___X_,
  ____XXXX,
  XX_XX___,
  X_X_X__X,
  _XX_X__X,
  X_XXXX__,
  ___X___X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00DB[ 18] = { /* code 00DB */
  _XXXX___,
  _XXXX_X_,
  _X______,
  X_X_X__X,
  XX_X__XX,
  _X_X__XX,
  X___XX_X,
  X_X_X_XX,
  __X_X___,
  XX__XX_X,
  X_XXX___,
  XX___XXX,
  _X__XXX_,
  XXXXX_X_,
  XX_XX_XX,
  _X_XX_XX,
  XX____XX,
  XX_X_X__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00DC[ 18] = { /* code 00DC */
  _XXX____,
  XXXXXXX_,
  __X_XX__,
  XX__X___,
  XX__X_X_,
  __X_XXX_,
  X__X___X,
  XXX___X_,
  X_X_XX_X,
  __X__XXX,
  X_XXX_X_,
  XX____X_,
  XX_X__X_,
  __XXXXXX,
  XX__X_X_,
  __X_XXXX,
  XXX_XX_X,
  XXX_X__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00DD[ 18] = { /* code 00DD */
  ___XXXXX,
  _XX___XX,
  ___X_X__,
  _X___XX_,
  X_X_XXX_,
  XX___X_X,
  X_X_XXX_,
  ___XX___,
  _X_XX__X,
  __XXX_XX,
  X__XXXXX,
  _XXX___X,
  _XXX__X_,
  X_X_X__X,
  XX_XXX_X,
  XXXXXXXX,
  XXXX_X__,
  X__XX___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00DE[ 18] = { /* code 00DE */
  _XXXX__X,
  _XXXX_XX,
  _____XXX,
  XXX_X___,
  XXXXXXX_,
  XXXXX___,
  X__XX__X,
  X__X_XX_,
  ___X_XXX,
  XXX_XX_X,
  X_XX__XX,
  XX_XX___,
  ___X_X__,
  XX__X__X,
  XXXX_XXX,
  __XXXXX_,
  X____X_X,
  _X_X_X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00DF[ 18] = { /* code 00DF */
  XXX___XX,
  _XXXX_XX,
  XXXXXXX_,
  XXX__XX_,
  _X_XX_X_,
  ___X___X,
  XXXX___X,
  XXXX_XXX,
  _X__X__X,
  XX_XX___,
  _XXX_XXX,
  XX_XXXXX,
  ___XX___,
  __X_XXXX,
  XXX_____,
  XXX___X_,
  _X___XXX,
  _XX___X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E0[ 18] = { /* code 00E0 */
  X_XXX_X_,
  _XX__XX_,
  X___XXX_,
  __XXXX_X,
  _XXX___X,
  _X______,
  ____X__X,
  X_X_X__X,
  X_XXX___,
  XXX_X_X_,
  ____X_XX,
  __X_X_X_,
  X_XXXX__,
  ___XX___,
  __X____X,
  XXXX__XX,
  _X_X____,
  _XXXX__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E1[ 18] = { /* code 00E1 */
  __X_X__X,
  XXXXXXX_,
  _____XXX,
  X___XXXX,
  X_XX___X,
  __X_XXXX,
  ______X_,
  X_XXXXXX,
  X__X_X__,
  _XX_X_XX,
  X_XXX___,
  X_X__X_X,
  _X__X___,
  XXXXX_X_,
  X_X_X___,
  X__XX__X,
  X_XXXX_X,
  XXXX_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E2[ 18] = { /* code 00E2 */
  ___XXXXX,
  _XXX__X_,
  X_XXXX__,
  XX___X__,
  X__XX_XX,
  XX__X_X_,
  X____XX_,
  _X__XXXX,
  __X_XXX_,
  XX__X_XX,
  __X__X__,
  XXXX___X,
  ______XX,
  X_X__XX_,
  __XX_XX_,
  _XX__X__,
  _XX_X___,
  __X_X__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E3[ 18] = { /* code 00E3 */
  X_____X_,
  _X__X_X_,
  X_X_X_XX,
  X_XXXXX_,
  _XX_XX__,
  _XXX__XX,
  ____X__X,
  _X_XXX__,
  X___XX__,
  XXXXXX__,
  XXXXXXX_,
  _X___XX_,
  X_XXXXX_,
  _X_XXX__,
  XX_XX_XX,
  XX_XXX__,
  XX_X_XX_,
  X_XX__XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E4[ 18] = { /* code 00E4 */
  _X___XX_,
  XX__X_X_,
  _XX_XXX_,
  _X_XXXXX,
  X_XX_XXX,
  X____XX_,
  XXX_X_X_,
  _XXXX_XX,
  _X_____X,
  _X_XX___,
  ___X_X__,
  X____XXX,
  __X_XX__,
  ___X____,
  __X_X_X_,
  __XX_XXX,
  _XXX_XXX,
  X__XXXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E5[ 18] = { /* code 00E5 */
  __X_____,
  _____XX_,
  X__X__X_,
  _X_XX_X_,
  XX__X_XX,
  _XXX_XX_,
  _X_XXX_X,
  X__XX___,
  X___X___,
  X_X_X_XX,
  X_XX_X_X,
  X_X_XX__,
  _XX_XXXX,
  _X___XX_,
  XXX_X_X_,
  __X_X_XX,
  __XX__X_,
  X_X_____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E6[ 18] = { /* code 00E6 */
  X___X_X_,
  ___X_XX_,
  X_XXXX__,
  XXX__XX_,
  _X_X_XXX,
  X____XXX,
  _____XXX,
  ____XX_X,
  _X__X_X_,
  X_XX_XX_,
  _X_XX__X,
  _X______,
  XX_XXX__,
  X_XXX_X_,
  XX__XX__,
  ___X__X_,
  X___X_XX,
  ______XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E7[ 18] = { /* code 00E7 */
  _X___XXX,
  XXXXXXX_,
  _______X,
  _XX__XXX,
  XX_XX_XX,
  __X____X,
  X____XX_,
  ______X_,
  ___XXXX_,
  __XX_X_X,
  ___X__XX,
  ____X_XX,
  XX_X__X_,
  X_XX_X__,
  ___XX__X,
  _XXXX__X,
  __XX___X,
  XXX_XX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E8[ 18] = { /* code 00E8 */
  _____XX_,
  ___XX___,
  __X_____,
  _XX___X_,
  XXX_____,
  _X__XX__,
  XXX__X_X,
  X_XX___X,
  _XXX___X,
  X_XXX__X,
  ___XXX__,
  _XXX_XXX,
  __XXX_X_,
  XX___XX_,
  ________,
  XXX_XX__,
  _X____XX,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00E9[ 18] = { /* code 00E9 */
  XXXXX___,
  _X__X_X_,
  XXX_____,
  ___X__XX,
  X_X__X__,
  _X_XX___,
  X_XXXXX_,
  ____X_XX,
  ____XXX_,
  XXXX____,
  XX_X____,
  X_X_X___,
  _X_X_XXX,
  _XX_XXX_,
  X_X_____,
  _XX__X__,
  __XX__XX,
  XX_XX_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00EA[ 18] = { /* code 00EA */
  X_X__XX_,
  _X__X___,
  ___XXXX_,
  XX_X_XX_,
  ____XX__,
  XX_XX__X,
  XXXX____,
  X_X_XXXX,
  X_XX__X_,
  X__XXX_X,
  XX__XX__,
  _X______,
  _X_X____,
  X_X__X__,
  _XX__XXX,
  XX___XX_,
  __X_XX__,
  XXXXX__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00EB[ 18] = { /* code 00EB */
  X__X_X_X,
  X_X_XX_X,
  X__X_X__,
  __X_X_X_,
  XXX___X_,
  XX_____X,
  _X__X___,
  X_X__XXX,
  ___X_XX_,
  XXX__XX_,
  XXXX__X_,
  X_XXX_XX,
  _X______,
  ___X___X,
  XX____XX,
  XXXX__X_,
  __X_XXX_,
  X_X_X_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00EC[ 18] = { /* code 00EC */
  X_X__X__,
  XXXXX__X,
  ____XX__,
  X__XX___,
  X_X____X,
  ___XX___,
  XX_XXXXX,
  XX__X_X_,
  _____XX_,
  _X_XX_XX,
  _XX__X__,
  _XXX_X_X,
  _X__X_X_,
  _X__XXXX,
  _XX_X_XX,
  XX_XX_X_,
  _X__X__X,
  _X__X_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00ED[ 18] = { /* code 00ED */
  __X_X_X_,
  X__XXX_X,
  _XXXX__X,
  XXXX__X_,
  X__XX___,
  XXXXXX__,
  X_X_X__X,
  _XX__X__,
  _X___XXX,
  X_XX_XX_,
  __X_XX_X,
  XX_X_XXX,
  X__X_X_X,
  _X_XXXX_,
  _XX_X_XX,
  XXXXX___,
  X____X__,
  XX__XX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00EE[ 18] = { /* code 00EE */
  __XXX___,
  _XX___XX,
  ___XX_XX,
  XX______,
  X_X__X__,
  X____X__,
  _X_X_XXX,
  X__XXXXX,
  __X_XX__,
  _XX__XXX,
  _X_X__X_,
  X_X_XXXX,
  XXX_XX__,
  _X__X_X_,
  X__X_XX_,
  __X_X___,
  XXX___X_,
  __XXX_X_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00EF[ 18] = { /* code 00EF */
  XX_XXX_X,
  _XXX__X_,
  X_X_XX_X,
  X__XX_XX,
  _XXX_X__,
  _XXXXX__,
  _X_XX_XX,
  __X_XX_X,
  XXX__X__,
  __X_XX_X,
  XX_XX_X_,
  XX_XX___,
  _XX_X___,
  XX__X___,
  X____X_X,
  X_X__XXX,
  _X_X_X_X,
  _X_X____};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F0[ 18] = { /* code 00F0 */
  XXXX___X,
  ___XX_X_,
  _X______,
  ___X_X__,
  XXX___XX,
  XX_X___X,
  XXX_____,
  _X___XXX,
  ___X_X__,
  _XX_X__X,
  _X_XX_X_,
  _XX_X___,
  _XXXX_XX,
  _XX_XX_X,
  ___X__XX,
  X_XX__X_,
  XXXXXXXX,
  _____X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F1[ 18] = { /* code 00F1 */
  _XX__XXX,
  XX___XXX,
  ___XXXXX,
  ____X_XX,
  _X__XXX_,
  _X__X__X,
  _XXX_XX_,
  __XXX___,
  X_XX_X_X,
  X_XX___X,
  ___X_X__,
  XXXXXXX_,
  _X_X____,
  XX_XX_X_,
  X_X___XX,
  XXX__X_X,
  __X___XX,
  XXXXX_XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F2[ 18] = { /* code 00F2 */
  X____XXX,
  X_XXX___,
  ____X__X,
  ___X____,
  X_XXX_XX,
  _X__X__X,
  X_XX__X_,
  _X_XXXXX,
  _X__X_X_,
  XX___X__,
  ___X_XX_,
  X_XXX___,
  _X_XX___,
  XX_XX_X_,
  _X__X_X_,
  X___XX_X,
  XXXX___X,
  X_XX__XX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F3[ 18] = { /* code 00F3 */
  _XXX__XX,
  X__X_X__,
  ____X_XX,
  __XXX__X,
  _X_XXX_X,
  X_X__X_X,
  _X__XXXX,
  XXXXX__X,
  X__XXXX_,
  XX_X_X_X,
  X_X_X__X,
  __XXX_X_,
  __XX__X_,
  XXX_X__X,
  XXX____X,
  __X_XXX_,
  __XXX_XX,
  _XX__X_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F4[ 18] = { /* code 00F4 */
  X__X__X_,
  _X__X__X,
  _X__XXX_,
  ____X_XX,
  XX_X__X_,
  X__X__XX,
  XX______,
  ______X_,
  ____X_X_,
  __X__X_X,
  _X_XX__X,
  __X_X_X_,
  X__X_XX_,
  _XXX_X_X,
  X______X,
  XXX___XX,
  X_____X_,
  ___XX__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F5[ 18] = { /* code 00F5 */
  X__X___X,
  _X_X____,
  XXXX_XXX,
  __X_____,
  XX_XX_XX,
  _X_XXX_X,
  XXXXXXX_,
  XXX__X__,
  _____X_X,
  ______X_,
  __X_XXXX,
  _____X__,
  X_____X_,
  X__XX___,
  _X__XXXX,
  __X_X___,
  X_____X_,
  _____XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F6[ 18] = { /* code 00F6 */
  _X_____X,
  _X_XX_X_,
  XX__X___,
  X___X_X_,
  _X_XXXX_,
  XXXXX_XX,
  _X_XX_X_,
  XX____XX,
  XX_XX___,
  _X__XX_X,
  X_XXX___,
  X__X_XX_,
  _XX_XX__,
  __XXX__X,
  _XX_XX_X,
  _X_X____,
  _XX__XX_,
  _XX__XXX};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F7[ 18] = { /* code 00F7 */
  _X_XX__X,
  XX__XXXX,
  _X_XXXX_,
  ___XX_XX,
  _____XX_,
  X___XXX_,
  _X_XX_XX,
  XXXX____,
  XXXXXX_X,
  XXX_XXXX,
  XXX___XX,
  ____X___,
  _XX___X_,
  _XXX_XX_,
  _X__X___,
  ____XXXX,
  ____XXXX,
  X___XX__};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F8[ 18] = { /* code 00F8 */
  _X_XXX__,
  _XX__X__,
  __X_XX_X,
  _X_XX__X,
  X_XXXX__,
  XXX_XXX_,
  ____X_X_,
  _XXX_XXX,
  XX_X_X_X,
  __XXX_XX,
  X_X_XX_X,
  __X_XXXX,
  _XX_XX_X,
  XX_XX_XX,
  ___X_X__,
  XX___X_X,
  ____X___,
  X_______};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00F9[ 18] = { /* code 00F9 */
  __XX_X_X,
  _XX__X_X,
  _XXX_X_X,
  _X_XX_X_,
  _X__XX_X,
  X___XXX_,
  ____X___,
  ____X___,
  XXXXXXX_,
  XXX___X_,
  XXXX_X_X,
  _____X_X,
  _X__X_XX,
  _____X__,
  _____XXX,
  X__XXXXX,
  __XXXXX_,
  X_XX_XX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00FA[ 18] = { /* code 00FA */
  ___XX_X_,
  XX_X____,
  XXXX__XX,
  ____X___,
  _XXXX___,
  _X_X__X_,
  ___X___X,
  __XXX_XX,
  XXXX_X__,
  X__XX_X_,
  XX____X_,
  _X__XX_X,
  _X_XX_X_,
  _X_XXX__,
  __XXX_X_,
  XX_XXXXX,
  ___X_XX_,
  _XX_XXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00FB[ 18] = { /* code 00FB */
  _XXX_XX_,
  _XXXX_XX,
  X_XX_X_X,
  __X_X___,
  ___X__X_,
  X__X_XXX,
  __X__X__,
  XX_X____,
  _X___X__,
  X__XXXX_,
  X_XX___X,
  _X____XX,
  X__XXX_X,
  __XX_X__,
  _X_X____,
  __XX____,
  XX__X_XX,
  _XXXXX_X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00FC[ 18] = { /* code 00FC */
  ___XXX__,
  _XXX__X_,
  XX_XXX_X,
  _XX_XXX_,
  _X___X_X,
  _X___X_X,
  XX__XX__,
  XX____XX,
  _X_XX__X,
  X_X___XX,
  ____X__X,
  X__XXX__,
  XX_X____,
  XX___X_X,
  X___XXX_,
  _____X__,
  XX_X_X_X,
  _X__X__X};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00FD[ 18] = { /* code 00FD */
  XX__X_X_,
  XX_XXXXX,
  X_XXXXX_,
  X_XXX__X,
  X_______,
  ___XXX__,
  XXXX__XX,
  X__XXX__,
  X___X_X_,
  ___XXXXX,
  __X__XX_,
  ____XXX_,
  _XXXXX__,
  X___X___,
  X____XXX,
  _XXX__X_,
  __XX_XXX,
  XX__XXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00FE[ 18] = { /* code 00FE */
  _X_XXX_X,
  _____X__,
  __X_X__X,
  XX_X___X,
  ____XX_X,
  _XXXXX__,
  _X_XX_X_,
  __XX__XX,
  X_XXXX__,
  X__XX_XX,
  X_XXXX_X,
  _XXX___X,
  _X__X___,
  XX__XX_X,
  __X__XX_,
  XX__X___,
  X____XXX,
  __X_XXX_};

GUI_CONST_STORAGE unsigned char acFontUbuntuMono18_00FF[ 18] = { /* code 00FF */
  XX__XXXX,
  ___X____,
  X_X__XX_,
  _XX___XX,
  X_XXX__X,
  XXX__X_X,
  XX____XX,
  X___XXX_,
  ___X_X_X,
  XXX_XXXX,
  _XX_X_X_,
  _X_X__XX,
  XX__X_XX,
  X__X__X_,
  XX__XXX_,
  ___XX_XX,
  _XX_XXXX,
  _XXXX__X};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontUbuntuMono18_CharInfo[192] = {
   {   8,   8,  1, acFontUbuntuMono18_0020 } /* code 0020 */
  ,{   8,   8,  1, acFontUbuntuMono18_0021 } /* code 0021 */
  ,{   8,   8,  1, acFontUbuntuMono18_0022 } /* code 0022 */
  ,{   8,   8,  1, acFontUbuntuMono18_0023 } /* code 0023 */
  ,{   8,   8,  1, acFontUbuntuMono18_0024 } /* code 0024 */
  ,{   8,   8,  1, acFontUbuntuMono18_0025 } /* code 0025 */
  ,{   8,   8,  1, acFontUbuntuMono18_0026 } /* code 0026 */
  ,{   8,   8,  1, acFontUbuntuMono18_0027 } /* code 0027 */
  ,{   8,   8,  1, acFontUbuntuMono18_0028 } /* code 0028 */
  ,{   8,   8,  1, acFontUbuntuMono18_0029 } /* code 0029 */
  ,{   8,   8,  1, acFontUbuntuMono18_002A } /* code 002A */
  ,{   8,   8,  1, acFontUbuntuMono18_002B } /* code 002B */
  ,{   8,   8,  1, acFontUbuntuMono18_002C } /* code 002C */
  ,{   8,   8,  1, acFontUbuntuMono18_002D } /* code 002D */
  ,{   8,   8,  1, acFontUbuntuMono18_002E } /* code 002E */
  ,{   8,   8,  1, acFontUbuntuMono18_002F } /* code 002F */
  ,{   8,   8,  1, acFontUbuntuMono18_0030 } /* code 0030 */
  ,{   8,   8,  1, acFontUbuntuMono18_0031 } /* code 0031 */
  ,{   8,   8,  1, acFontUbuntuMono18_0032 } /* code 0032 */
  ,{   8,   8,  1, acFontUbuntuMono18_0033 } /* code 0033 */
  ,{   8,   8,  1, acFontUbuntuMono18_0034 } /* code 0034 */
  ,{   8,   8,  1, acFontUbuntuMono18_0035 } /* code 0035 */
  ,{   8,   8,  1, acFontUbuntuMono18_0036 } /* code 0036 */
  ,{   8,   8,  1, acFontUbuntuMono18_0037 } /* code 0037 */
  ,{   8,   8,  1, acFontUbuntuMono18_0038 } /* code 0038 */
  ,{   8,   8,  1, acFontUbuntuMono18_0039 } /* code 0039 */
  ,{   8,   8,  1, acFontUbuntuMono18_003A } /* code 003A */
  ,{   8,   8,  1, acFontUbuntuMono18_003B } /* code 003B */
  ,{   8,   8,  1, acFontUbuntuMono18_003C } /* code 003C */
  ,{   8,   8,  1, acFontUbuntuMono18_003D } /* code 003D */
  ,{   8,   8,  1, acFontUbuntuMono18_003E } /* code 003E */
  ,{   8,   8,  1, acFontUbuntuMono18_003F } /* code 003F */
  ,{   8,   8,  1, acFontUbuntuMono18_0040 } /* code 0040 */
  ,{   8,   8,  1, acFontUbuntuMono18_0041 } /* code 0041 */
  ,{   8,   8,  1, acFontUbuntuMono18_0042 } /* code 0042 */
  ,{   8,   8,  1, acFontUbuntuMono18_0043 } /* code 0043 */
  ,{   8,   8,  1, acFontUbuntuMono18_0044 } /* code 0044 */
  ,{   8,   8,  1, acFontUbuntuMono18_0045 } /* code 0045 */
  ,{   8,   8,  1, acFontUbuntuMono18_0046 } /* code 0046 */
  ,{   8,   8,  1, acFontUbuntuMono18_0047 } /* code 0047 */
  ,{   8,   8,  1, acFontUbuntuMono18_0048 } /* code 0048 */
  ,{   8,   8,  1, acFontUbuntuMono18_0049 } /* code 0049 */
  ,{   8,   8,  1, acFontUbuntuMono18_004A } /* code 004A */
  ,{   8,   8,  1, acFontUbuntuMono18_004B } /* code 004B */
  ,{   8,   8,  1, acFontUbuntuMono18_004C } /* code 004C */
  ,{   8,   8,  1, acFontUbuntuMono18_004D } /* code 004D */
  ,{   8,   8,  1, acFontUbuntuMono18_004E } /* code 004E */
  ,{   8,   8,  1, acFontUbuntuMono18_004F } /* code 004F */
  ,{   8,   8,  1, acFontUbuntuMono18_0050 } /* code 0050 */
  ,{   8,   8,  1, acFontUbuntuMono18_0051 } /* code 0051 */
  ,{   8,   8,  1, acFontUbuntuMono18_0052 } /* code 0052 */
  ,{   8,   8,  1, acFontUbuntuMono18_0053 } /* code 0053 */
  ,{   8,   8,  1, acFontUbuntuMono18_0054 } /* code 0054 */
  ,{   8,   8,  1, acFontUbuntuMono18_0055 } /* code 0055 */
  ,{   8,   8,  1, acFontUbuntuMono18_0056 } /* code 0056 */
  ,{   8,   8,  1, acFontUbuntuMono18_0057 } /* code 0057 */
  ,{   8,   8,  1, acFontUbuntuMono18_0058 } /* code 0058 */
  ,{   8,   8,  1, acFontUbuntuMono18_0059 } /* code 0059 */
  ,{   8,   8,  1, acFontUbuntuMono18_005A } /* code 005A */
  ,{   8,   8,  1, acFontUbuntuMono18_005B } /* code 005B */
  ,{   8,   8,  1, acFontUbuntuMono18_005C } /* code 005C */
  ,{   8,   8,  1, acFontUbuntuMono18_005D } /* code 005D */
  ,{   8,   8,  1, acFontUbuntuMono18_005E } /* code 005E */
  ,{   8,   8,  1, acFontUbuntuMono18_005F } /* code 005F */
  ,{   8,   8,  1, acFontUbuntuMono18_0060 } /* code 0060 */
  ,{   8,   8,  1, acFontUbuntuMono18_0061 } /* code 0061 */
  ,{   8,   8,  1, acFontUbuntuMono18_0062 } /* code 0062 */
  ,{   8,   8,  1, acFontUbuntuMono18_0063 } /* code 0063 */
  ,{   8,   8,  1, acFontUbuntuMono18_0064 } /* code 0064 */
  ,{   8,   8,  1, acFontUbuntuMono18_0065 } /* code 0065 */
  ,{   8,   8,  1, acFontUbuntuMono18_0066 } /* code 0066 */
  ,{   8,   8,  1, acFontUbuntuMono18_0067 } /* code 0067 */
  ,{   8,   8,  1, acFontUbuntuMono18_0068 } /* code 0068 */
  ,{   8,   8,  1, acFontUbuntuMono18_0069 } /* code 0069 */
  ,{   8,   8,  1, acFontUbuntuMono18_006A } /* code 006A */
  ,{   8,   8,  1, acFontUbuntuMono18_006B } /* code 006B */
  ,{   8,   8,  1, acFontUbuntuMono18_006C } /* code 006C */
  ,{   8,   8,  1, acFontUbuntuMono18_006D } /* code 006D */
  ,{   8,   8,  1, acFontUbuntuMono18_006E } /* code 006E */
  ,{   8,   8,  1, acFontUbuntuMono18_006F } /* code 006F */
  ,{   8,   8,  1, acFontUbuntuMono18_0070 } /* code 0070 */
  ,{   8,   8,  1, acFontUbuntuMono18_0071 } /* code 0071 */
  ,{   8,   8,  1, acFontUbuntuMono18_0072 } /* code 0072 */
  ,{   8,   8,  1, acFontUbuntuMono18_0073 } /* code 0073 */
  ,{   8,   8,  1, acFontUbuntuMono18_0074 } /* code 0074 */
  ,{   8,   8,  1, acFontUbuntuMono18_0075 } /* code 0075 */
  ,{   8,   8,  1, acFontUbuntuMono18_0076 } /* code 0076 */
  ,{   8,   8,  1, acFontUbuntuMono18_0077 } /* code 0077 */
  ,{   8,   8,  1, acFontUbuntuMono18_0078 } /* code 0078 */
  ,{   8,   8,  1, acFontUbuntuMono18_0079 } /* code 0079 */
  ,{   8,   8,  1, acFontUbuntuMono18_007A } /* code 007A */
  ,{   8,   8,  1, acFontUbuntuMono18_007B } /* code 007B */
  ,{   8,   8,  1, acFontUbuntuMono18_007C } /* code 007C */
  ,{   8,   8,  1, acFontUbuntuMono18_007D } /* code 007D */
  ,{   8,   8,  1, acFontUbuntuMono18_007E } /* code 007E */
  ,{   5,   5,  1, acFontUbuntuMono18_007F } /* code 007F */
  ,{   8,   8,  1, acFontUbuntuMono18_00A0 } /* code 00A0 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A1 } /* code 00A1 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A2 } /* code 00A2 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A3 } /* code 00A3 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A4 } /* code 00A4 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A5 } /* code 00A5 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A6 } /* code 00A6 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A7 } /* code 00A7 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A8 } /* code 00A8 */
  ,{   8,   8,  1, acFontUbuntuMono18_00A9 } /* code 00A9 */
  ,{   8,   8,  1, acFontUbuntuMono18_00AA } /* code 00AA */
  ,{   8,   8,  1, acFontUbuntuMono18_00AB } /* code 00AB */
  ,{   8,   8,  1, acFontUbuntuMono18_00AC } /* code 00AC */
  ,{   8,   8,  1, acFontUbuntuMono18_00AD } /* code 00AD */
  ,{   8,   8,  1, acFontUbuntuMono18_00AE } /* code 00AE */
  ,{   8,   8,  1, acFontUbuntuMono18_00AF } /* code 00AF */
  ,{   8,   8,  1, acFontUbuntuMono18_00B0 } /* code 00B0 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B1 } /* code 00B1 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B2 } /* code 00B2 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B3 } /* code 00B3 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B4 } /* code 00B4 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B5 } /* code 00B5 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B6 } /* code 00B6 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B7 } /* code 00B7 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B8 } /* code 00B8 */
  ,{   8,   8,  1, acFontUbuntuMono18_00B9 } /* code 00B9 */
  ,{   8,   8,  1, acFontUbuntuMono18_00BA } /* code 00BA */
  ,{   8,   8,  1, acFontUbuntuMono18_00BB } /* code 00BB */
  ,{   8,   8,  1, acFontUbuntuMono18_00BC } /* code 00BC */
  ,{   8,   8,  1, acFontUbuntuMono18_00BD } /* code 00BD */
  ,{   8,   8,  1, acFontUbuntuMono18_00BE } /* code 00BE */
  ,{   8,   8,  1, acFontUbuntuMono18_00BF } /* code 00BF */
  ,{   8,   8,  1, acFontUbuntuMono18_00C0 } /* code 00C0 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C1 } /* code 00C1 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C2 } /* code 00C2 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C3 } /* code 00C3 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C4 } /* code 00C4 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C5 } /* code 00C5 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C6 } /* code 00C6 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C7 } /* code 00C7 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C8 } /* code 00C8 */
  ,{   8,   8,  1, acFontUbuntuMono18_00C9 } /* code 00C9 */
  ,{   8,   8,  1, acFontUbuntuMono18_00CA } /* code 00CA */
  ,{   8,   8,  1, acFontUbuntuMono18_00CB } /* code 00CB */
  ,{   8,   8,  1, acFontUbuntuMono18_00CC } /* code 00CC */
  ,{   8,   8,  1, acFontUbuntuMono18_00CD } /* code 00CD */
  ,{   8,   8,  1, acFontUbuntuMono18_00CE } /* code 00CE */
  ,{   8,   8,  1, acFontUbuntuMono18_00CF } /* code 00CF */
  ,{   8,   8,  1, acFontUbuntuMono18_00D0 } /* code 00D0 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D1 } /* code 00D1 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D2 } /* code 00D2 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D3 } /* code 00D3 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D4 } /* code 00D4 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D5 } /* code 00D5 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D6 } /* code 00D6 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D7 } /* code 00D7 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D8 } /* code 00D8 */
  ,{   8,   8,  1, acFontUbuntuMono18_00D9 } /* code 00D9 */
  ,{   8,   8,  1, acFontUbuntuMono18_00DA } /* code 00DA */
  ,{   8,   8,  1, acFontUbuntuMono18_00DB } /* code 00DB */
  ,{   8,   8,  1, acFontUbuntuMono18_00DC } /* code 00DC */
  ,{   8,   8,  1, acFontUbuntuMono18_00DD } /* code 00DD */
  ,{   8,   8,  1, acFontUbuntuMono18_00DE } /* code 00DE */
  ,{   8,   8,  1, acFontUbuntuMono18_00DF } /* code 00DF */
  ,{   8,   8,  1, acFontUbuntuMono18_00E0 } /* code 00E0 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E1 } /* code 00E1 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E2 } /* code 00E2 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E3 } /* code 00E3 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E4 } /* code 00E4 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E5 } /* code 00E5 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E6 } /* code 00E6 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E7 } /* code 00E7 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E8 } /* code 00E8 */
  ,{   8,   8,  1, acFontUbuntuMono18_00E9 } /* code 00E9 */
  ,{   8,   8,  1, acFontUbuntuMono18_00EA } /* code 00EA */
  ,{   8,   8,  1, acFontUbuntuMono18_00EB } /* code 00EB */
  ,{   8,   8,  1, acFontUbuntuMono18_00EC } /* code 00EC */
  ,{   8,   8,  1, acFontUbuntuMono18_00ED } /* code 00ED */
  ,{   8,   8,  1, acFontUbuntuMono18_00EE } /* code 00EE */
  ,{   8,   8,  1, acFontUbuntuMono18_00EF } /* code 00EF */
  ,{   8,   8,  1, acFontUbuntuMono18_00F0 } /* code 00F0 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F1 } /* code 00F1 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F2 } /* code 00F2 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F3 } /* code 00F3 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F4 } /* code 00F4 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F5 } /* code 00F5 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F6 } /* code 00F6 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F7 } /* code 00F7 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F8 } /* code 00F8 */
  ,{   8,   8,  1, acFontUbuntuMono18_00F9 } /* code 00F9 */
  ,{   8,   8,  1, acFontUbuntuMono18_00FA } /* code 00FA */
  ,{   8,   8,  1, acFontUbuntuMono18_00FB } /* code 00FB */
  ,{   8,   8,  1, acFontUbuntuMono18_00FC } /* code 00FC */
  ,{   8,   8,  1, acFontUbuntuMono18_00FD } /* code 00FD */
  ,{   8,   8,  1, acFontUbuntuMono18_00FE } /* code 00FE */
  ,{   8,   8,  1, acFontUbuntuMono18_00FF } /* code 00FF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontUbuntuMono18_Prop2 = {
   0x00A0 /* first character */
  ,0x00FF /* last character  */
  ,&GUI_FontUbuntuMono18_CharInfo[ 96] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP*)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontUbuntuMono18_Prop1 = {
   0x0020 /* first character */
  ,0x007F /* last character  */
  ,&GUI_FontUbuntuMono18_CharInfo[  0] /* address of first character */
  ,&GUI_FontUbuntuMono18_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontUbuntuMono18 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,18 /* height of font  */
  ,18 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,&GUI_FontUbuntuMono18_Prop1
};

